// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/shahbridge/v1/query.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_shahcoin_shahbridge_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahbridge_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahbridge_v1_query_proto_rawDescGZIP(), []int{0}
}

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_shahcoin_shahbridge_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahbridge_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahbridge_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// QueryChannelsRequest is the request type for Query/Channels
type QueryChannelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryChannelsRequest) Reset() {
	*x = QueryChannelsRequest{}
	mi := &file_shahcoin_shahbridge_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChannelsRequest) ProtoMessage() {}

func (x *QueryChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahbridge_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChannelsRequest.ProtoReflect.Descriptor instead.
func (*QueryChannelsRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahbridge_v1_query_proto_rawDescGZIP(), []int{2}
}

// QueryChannelsResponse is the response type for Query/Channels
type QueryChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []*ChannelMetadata     `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryChannelsResponse) Reset() {
	*x = QueryChannelsResponse{}
	mi := &file_shahcoin_shahbridge_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChannelsResponse) ProtoMessage() {}

func (x *QueryChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahbridge_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChannelsResponse.ProtoReflect.Descriptor instead.
func (*QueryChannelsResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahbridge_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryChannelsResponse) GetChannels() []*ChannelMetadata {
	if x != nil {
		return x.Channels
	}
	return nil
}

var File_shahcoin_shahbridge_v1_query_proto protoreflect.FileDescriptor

const file_shahcoin_shahbridge_v1_query_proto_rawDesc = "" +
	"\n" +
	"\"shahcoin/shahbridge/v1/query.proto\x12\x16shahcoin.shahbridge.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\x1a#shahcoin/shahbridge/v1/params.proto\x1a$shahcoin/shahbridge/v1/genesis.proto\"\x14\n" +
	"\x12QueryParamsRequest\"S\n" +
	"\x13QueryParamsResponse\x12<\n" +
	"\x06params\x18\x01 \x01(\v2\x1e.shahcoin.shahbridge.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\"\x16\n" +
	"\x14QueryChannelsRequest\"b\n" +
	"\x15QueryChannelsResponse\x12I\n" +
	"\bchannels\x18\x01 \x03(\v2'.shahcoin.shahbridge.v1.ChannelMetadataB\x04\xc8\xde\x1f\x00R\bchannels2\xa7\x02\n" +
	"\x05Query\x12\x89\x01\n" +
	"\x06Params\x12*.shahcoin.shahbridge.v1.QueryParamsRequest\x1a+.shahcoin.shahbridge.v1.QueryParamsResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/shahcoin/shahbridge/v1/params\x12\x91\x01\n" +
	"\bChannels\x12,.shahcoin.shahbridge.v1.QueryChannelsRequest\x1a-.shahcoin.shahbridge.v1.QueryChannelsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /shahcoin/shahbridge/v1/channelsB1Z/github.com/shahcoin/shahcoin/x/shahbridge/typesb\x06proto3"

var (
	file_shahcoin_shahbridge_v1_query_proto_rawDescOnce sync.Once
	file_shahcoin_shahbridge_v1_query_proto_rawDescData []byte
)

func file_shahcoin_shahbridge_v1_query_proto_rawDescGZIP() []byte {
	file_shahcoin_shahbridge_v1_query_proto_rawDescOnce.Do(func() {
		file_shahcoin_shahbridge_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_shahbridge_v1_query_proto_rawDesc), len(file_shahcoin_shahbridge_v1_query_proto_rawDesc)))
	})
	return file_shahcoin_shahbridge_v1_query_proto_rawDescData
}

var file_shahcoin_shahbridge_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shahcoin_shahbridge_v1_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),    // 0: shahcoin.shahbridge.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),   // 1: shahcoin.shahbridge.v1.QueryParamsResponse
	(*QueryChannelsRequest)(nil),  // 2: shahcoin.shahbridge.v1.QueryChannelsRequest
	(*QueryChannelsResponse)(nil), // 3: shahcoin.shahbridge.v1.QueryChannelsResponse
	(*Params)(nil),                // 4: shahcoin.shahbridge.v1.Params
	(*ChannelMetadata)(nil),       // 5: shahcoin.shahbridge.v1.ChannelMetadata
}
var file_shahcoin_shahbridge_v1_query_proto_depIdxs = []int32{
	4, // 0: shahcoin.shahbridge.v1.QueryParamsResponse.params:type_name -> shahcoin.shahbridge.v1.Params
	5, // 1: shahcoin.shahbridge.v1.QueryChannelsResponse.channels:type_name -> shahcoin.shahbridge.v1.ChannelMetadata
	0, // 2: shahcoin.shahbridge.v1.Query.Params:input_type -> shahcoin.shahbridge.v1.QueryParamsRequest
	2, // 3: shahcoin.shahbridge.v1.Query.Channels:input_type -> shahcoin.shahbridge.v1.QueryChannelsRequest
	1, // 4: shahcoin.shahbridge.v1.Query.Params:output_type -> shahcoin.shahbridge.v1.QueryParamsResponse
	3, // 5: shahcoin.shahbridge.v1.Query.Channels:output_type -> shahcoin.shahbridge.v1.QueryChannelsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shahcoin_shahbridge_v1_query_proto_init() }
func file_shahcoin_shahbridge_v1_query_proto_init() {
	if File_shahcoin_shahbridge_v1_query_proto != nil {
		return
	}
	file_shahcoin_shahbridge_v1_params_proto_init()
	file_shahcoin_shahbridge_v1_genesis_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_shahbridge_v1_query_proto_rawDesc), len(file_shahcoin_shahbridge_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shahcoin_shahbridge_v1_query_proto_goTypes,
		DependencyIndexes: file_shahcoin_shahbridge_v1_query_proto_depIdxs,
		MessageInfos:      file_shahcoin_shahbridge_v1_query_proto_msgTypes,
	}.Build()
	File_shahcoin_shahbridge_v1_query_proto = out.File
	file_shahcoin_shahbridge_v1_query_proto_goTypes = nil
	file_shahcoin_shahbridge_v1_query_proto_depIdxs = nil
}
