// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/shahbridge/v1/genesis.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenesisState defines the shahbridge module's genesis state.
type GenesisState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// params defines all the parameters of the module.
	Params *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	// channel_metadata holds channel metadata
	Channels      []*ChannelMetadata `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_shahcoin_shahbridge_v1_genesis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahbridge_v1_genesis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahbridge_v1_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *GenesisState) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenesisState) GetChannels() []*ChannelMetadata {
	if x != nil {
		return x.Channels
	}
	return nil
}

// ChannelMetadata holds metadata for IBC channels
type ChannelMetadata struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ChannelId             string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	PortId                string                 `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	CounterpartyChannelId string                 `protobuf:"bytes,3,opt,name=counterparty_channel_id,json=counterpartyChannelId,proto3" json:"counterparty_channel_id,omitempty"`
	CounterpartyPortId    string                 `protobuf:"bytes,4,opt,name=counterparty_port_id,json=counterpartyPortId,proto3" json:"counterparty_port_id,omitempty"`
	ConnectionId          string                 `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ChainName             string                 `protobuf:"bytes,6,opt,name=chain_name,json=chainName,proto3" json:"chain_name,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ChannelMetadata) Reset() {
	*x = ChannelMetadata{}
	mi := &file_shahcoin_shahbridge_v1_genesis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMetadata) ProtoMessage() {}

func (x *ChannelMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahbridge_v1_genesis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMetadata.ProtoReflect.Descriptor instead.
func (*ChannelMetadata) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahbridge_v1_genesis_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelMetadata) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelMetadata) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *ChannelMetadata) GetCounterpartyChannelId() string {
	if x != nil {
		return x.CounterpartyChannelId
	}
	return ""
}

func (x *ChannelMetadata) GetCounterpartyPortId() string {
	if x != nil {
		return x.CounterpartyPortId
	}
	return ""
}

func (x *ChannelMetadata) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ChannelMetadata) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

var File_shahcoin_shahbridge_v1_genesis_proto protoreflect.FileDescriptor

const file_shahcoin_shahbridge_v1_genesis_proto_rawDesc = "" +
	"\n" +
	"$shahcoin/shahbridge/v1/genesis.proto\x12\x16shahcoin.shahbridge.v1\x1a\x14gogoproto/gogo.proto\x1a#shahcoin/shahbridge/v1/params.proto\"\x97\x01\n" +
	"\fGenesisState\x12<\n" +
	"\x06params\x18\x01 \x01(\v2\x1e.shahcoin.shahbridge.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\x12I\n" +
	"\bchannels\x18\x02 \x03(\v2'.shahcoin.shahbridge.v1.ChannelMetadataB\x04\xc8\xde\x1f\x00R\bchannels\"\xf7\x01\n" +
	"\x0fChannelMetadata\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x17\n" +
	"\aport_id\x18\x02 \x01(\tR\x06portId\x126\n" +
	"\x17counterparty_channel_id\x18\x03 \x01(\tR\x15counterpartyChannelId\x120\n" +
	"\x14counterparty_port_id\x18\x04 \x01(\tR\x12counterpartyPortId\x12#\n" +
	"\rconnection_id\x18\x05 \x01(\tR\fconnectionId\x12\x1d\n" +
	"\n" +
	"chain_name\x18\x06 \x01(\tR\tchainNameB1Z/github.com/shahcoin/shahcoin/x/shahbridge/typesb\x06proto3"

var (
	file_shahcoin_shahbridge_v1_genesis_proto_rawDescOnce sync.Once
	file_shahcoin_shahbridge_v1_genesis_proto_rawDescData []byte
)

func file_shahcoin_shahbridge_v1_genesis_proto_rawDescGZIP() []byte {
	file_shahcoin_shahbridge_v1_genesis_proto_rawDescOnce.Do(func() {
		file_shahcoin_shahbridge_v1_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_shahbridge_v1_genesis_proto_rawDesc), len(file_shahcoin_shahbridge_v1_genesis_proto_rawDesc)))
	})
	return file_shahcoin_shahbridge_v1_genesis_proto_rawDescData
}

var file_shahcoin_shahbridge_v1_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shahcoin_shahbridge_v1_genesis_proto_goTypes = []any{
	(*GenesisState)(nil),    // 0: shahcoin.shahbridge.v1.GenesisState
	(*ChannelMetadata)(nil), // 1: shahcoin.shahbridge.v1.ChannelMetadata
	(*Params)(nil),          // 2: shahcoin.shahbridge.v1.Params
}
var file_shahcoin_shahbridge_v1_genesis_proto_depIdxs = []int32{
	2, // 0: shahcoin.shahbridge.v1.GenesisState.params:type_name -> shahcoin.shahbridge.v1.Params
	1, // 1: shahcoin.shahbridge.v1.GenesisState.channels:type_name -> shahcoin.shahbridge.v1.ChannelMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shahcoin_shahbridge_v1_genesis_proto_init() }
func file_shahcoin_shahbridge_v1_genesis_proto_init() {
	if File_shahcoin_shahbridge_v1_genesis_proto != nil {
		return
	}
	file_shahcoin_shahbridge_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_shahbridge_v1_genesis_proto_rawDesc), len(file_shahcoin_shahbridge_v1_genesis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shahcoin_shahbridge_v1_genesis_proto_goTypes,
		DependencyIndexes: file_shahcoin_shahbridge_v1_genesis_proto_depIdxs,
		MessageInfos:      file_shahcoin_shahbridge_v1_genesis_proto_msgTypes,
	}.Build()
	File_shahcoin_shahbridge_v1_genesis_proto = out.File
	file_shahcoin_shahbridge_v1_genesis_proto_goTypes = nil
	file_shahcoin_shahbridge_v1_genesis_proto_depIdxs = nil
}
