// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/fees/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgUpdateParams updates params
type MsgUpdateParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params        *Params                `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_shahcoin_fees_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_fees_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_shahcoin_fees_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_shahcoin_fees_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_fees_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_fees_v1_tx_proto_rawDescGZIP(), []int{1}
}

var File_shahcoin_fees_v1_tx_proto protoreflect.FileDescriptor

const file_shahcoin_fees_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x19shahcoin/fees/v1/tx.proto\x12\x10shahcoin.fees.v1\x1a\x17cosmos/msg/v1/msg.proto\x1a\x14gogoproto/gogo.proto\x1a\x1dshahcoin/fees/v1/params.proto\"w\n" +
	"\x0fMsgUpdateParams\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x126\n" +
	"\x06params\x18\x02 \x01(\v2\x18.shahcoin.fees.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params:\x0e\x82\xe7\xb0*\tauthority\"\x19\n" +
	"\x17MsgUpdateParamsResponse2j\n" +
	"\x03Msg\x12\\\n" +
	"\fUpdateParams\x12!.shahcoin.fees.v1.MsgUpdateParams\x1a).shahcoin.fees.v1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01B+Z)github.com/shahcoin/shahcoin/x/fees/typesb\x06proto3"

var (
	file_shahcoin_fees_v1_tx_proto_rawDescOnce sync.Once
	file_shahcoin_fees_v1_tx_proto_rawDescData []byte
)

func file_shahcoin_fees_v1_tx_proto_rawDescGZIP() []byte {
	file_shahcoin_fees_v1_tx_proto_rawDescOnce.Do(func() {
		file_shahcoin_fees_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_fees_v1_tx_proto_rawDesc), len(file_shahcoin_fees_v1_tx_proto_rawDesc)))
	})
	return file_shahcoin_fees_v1_tx_proto_rawDescData
}

var file_shahcoin_fees_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shahcoin_fees_v1_tx_proto_goTypes = []any{
	(*MsgUpdateParams)(nil),         // 0: shahcoin.fees.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil), // 1: shahcoin.fees.v1.MsgUpdateParamsResponse
	(*Params)(nil),                  // 2: shahcoin.fees.v1.Params
}
var file_shahcoin_fees_v1_tx_proto_depIdxs = []int32{
	2, // 0: shahcoin.fees.v1.MsgUpdateParams.params:type_name -> shahcoin.fees.v1.Params
	0, // 1: shahcoin.fees.v1.Msg.UpdateParams:input_type -> shahcoin.fees.v1.MsgUpdateParams
	1, // 2: shahcoin.fees.v1.Msg.UpdateParams:output_type -> shahcoin.fees.v1.MsgUpdateParamsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shahcoin_fees_v1_tx_proto_init() }
func file_shahcoin_fees_v1_tx_proto_init() {
	if File_shahcoin_fees_v1_tx_proto != nil {
		return
	}
	file_shahcoin_fees_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_fees_v1_tx_proto_rawDesc), len(file_shahcoin_fees_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shahcoin_fees_v1_tx_proto_goTypes,
		DependencyIndexes: file_shahcoin_fees_v1_tx_proto_depIdxs,
		MessageInfos:      file_shahcoin_fees_v1_tx_proto_msgTypes,
	}.Build()
	File_shahcoin_fees_v1_tx_proto = out.File
	file_shahcoin_fees_v1_tx_proto_goTypes = nil
	file_shahcoin_fees_v1_tx_proto_depIdxs = nil
}
