// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/treasury/v1/query.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_shahcoin_treasury_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_query_proto_rawDescGZIP(), []int{0}
}

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_shahcoin_treasury_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// QueryReservesRequest is the request type for Query/Reserves
type QueryReservesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryReservesRequest) Reset() {
	*x = QueryReservesRequest{}
	mi := &file_shahcoin_treasury_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReservesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReservesRequest) ProtoMessage() {}

func (x *QueryReservesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReservesRequest.ProtoReflect.Descriptor instead.
func (*QueryReservesRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_query_proto_rawDescGZIP(), []int{2}
}

// QueryReservesResponse is the response type for Query/Reserves
type QueryReservesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReserveShah    string                 `protobuf:"bytes,1,opt,name=reserve_shah,json=reserveShah,proto3" json:"reserve_shah,omitempty"`
	ReserveShahusd string                 `protobuf:"bytes,2,opt,name=reserve_shahusd,json=reserveShahusd,proto3" json:"reserve_shahusd,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryReservesResponse) Reset() {
	*x = QueryReservesResponse{}
	mi := &file_shahcoin_treasury_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReservesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReservesResponse) ProtoMessage() {}

func (x *QueryReservesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReservesResponse.ProtoReflect.Descriptor instead.
func (*QueryReservesResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryReservesResponse) GetReserveShah() string {
	if x != nil {
		return x.ReserveShah
	}
	return ""
}

func (x *QueryReservesResponse) GetReserveShahusd() string {
	if x != nil {
		return x.ReserveShahusd
	}
	return ""
}

// QueryPolicyRateRequest is the request type for Query/PolicyRate
type QueryPolicyRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPolicyRateRequest) Reset() {
	*x = QueryPolicyRateRequest{}
	mi := &file_shahcoin_treasury_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPolicyRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPolicyRateRequest) ProtoMessage() {}

func (x *QueryPolicyRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPolicyRateRequest.ProtoReflect.Descriptor instead.
func (*QueryPolicyRateRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_query_proto_rawDescGZIP(), []int{4}
}

// QueryPolicyRateResponse is the response type for Query/PolicyRate
type QueryPolicyRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          string                 `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPolicyRateResponse) Reset() {
	*x = QueryPolicyRateResponse{}
	mi := &file_shahcoin_treasury_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPolicyRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPolicyRateResponse) ProtoMessage() {}

func (x *QueryPolicyRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPolicyRateResponse.ProtoReflect.Descriptor instead.
func (*QueryPolicyRateResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryPolicyRateResponse) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

var File_shahcoin_treasury_v1_query_proto protoreflect.FileDescriptor

const file_shahcoin_treasury_v1_query_proto_rawDesc = "" +
	"\n" +
	" shahcoin/treasury/v1/query.proto\x12\x14shahcoin.treasury.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\x1a!shahcoin/treasury/v1/params.proto\"\x14\n" +
	"\x12QueryParamsRequest\"Q\n" +
	"\x13QueryParamsResponse\x12:\n" +
	"\x06params\x18\x01 \x01(\v2\x1c.shahcoin.treasury.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\"\x16\n" +
	"\x14QueryReservesRequest\"\xa1\x01\n" +
	"\x15QueryReservesResponse\x12@\n" +
	"\freserve_shah\x18\x01 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\vreserveShah\x12F\n" +
	"\x0freserve_shahusd\x18\x02 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\x0ereserveShahusd\"\x18\n" +
	"\x16QueryPolicyRateRequest\"R\n" +
	"\x17QueryPolicyRateResponse\x127\n" +
	"\x04rate\x18\x01 \x01(\tB#\xc8\xde\x1f\x00\xda\xde\x1f\x1bcosmossdk.io/math.LegacyDecR\x04rate2\xb2\x03\n" +
	"\x05Query\x12\x83\x01\n" +
	"\x06Params\x12(.shahcoin.treasury.v1.QueryParamsRequest\x1a).shahcoin.treasury.v1.QueryParamsResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/shahcoin/treasury/v1/params\x12\x8b\x01\n" +
	"\bReserves\x12*.shahcoin.treasury.v1.QueryReservesRequest\x1a+.shahcoin.treasury.v1.QueryReservesResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/shahcoin/treasury/v1/reserves\x12\x94\x01\n" +
	"\n" +
	"PolicyRate\x12,.shahcoin.treasury.v1.QueryPolicyRateRequest\x1a-.shahcoin.treasury.v1.QueryPolicyRateResponse\")\x82\xd3\xe4\x93\x02#\x12!/shahcoin/treasury/v1/policy_rateB/Z-github.com/shahcoin/shahcoin/x/treasury/typesb\x06proto3"

var (
	file_shahcoin_treasury_v1_query_proto_rawDescOnce sync.Once
	file_shahcoin_treasury_v1_query_proto_rawDescData []byte
)

func file_shahcoin_treasury_v1_query_proto_rawDescGZIP() []byte {
	file_shahcoin_treasury_v1_query_proto_rawDescOnce.Do(func() {
		file_shahcoin_treasury_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_treasury_v1_query_proto_rawDesc), len(file_shahcoin_treasury_v1_query_proto_rawDesc)))
	})
	return file_shahcoin_treasury_v1_query_proto_rawDescData
}

var file_shahcoin_treasury_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shahcoin_treasury_v1_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),      // 0: shahcoin.treasury.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),     // 1: shahcoin.treasury.v1.QueryParamsResponse
	(*QueryReservesRequest)(nil),    // 2: shahcoin.treasury.v1.QueryReservesRequest
	(*QueryReservesResponse)(nil),   // 3: shahcoin.treasury.v1.QueryReservesResponse
	(*QueryPolicyRateRequest)(nil),  // 4: shahcoin.treasury.v1.QueryPolicyRateRequest
	(*QueryPolicyRateResponse)(nil), // 5: shahcoin.treasury.v1.QueryPolicyRateResponse
	(*Params)(nil),                  // 6: shahcoin.treasury.v1.Params
}
var file_shahcoin_treasury_v1_query_proto_depIdxs = []int32{
	6, // 0: shahcoin.treasury.v1.QueryParamsResponse.params:type_name -> shahcoin.treasury.v1.Params
	0, // 1: shahcoin.treasury.v1.Query.Params:input_type -> shahcoin.treasury.v1.QueryParamsRequest
	2, // 2: shahcoin.treasury.v1.Query.Reserves:input_type -> shahcoin.treasury.v1.QueryReservesRequest
	4, // 3: shahcoin.treasury.v1.Query.PolicyRate:input_type -> shahcoin.treasury.v1.QueryPolicyRateRequest
	1, // 4: shahcoin.treasury.v1.Query.Params:output_type -> shahcoin.treasury.v1.QueryParamsResponse
	3, // 5: shahcoin.treasury.v1.Query.Reserves:output_type -> shahcoin.treasury.v1.QueryReservesResponse
	5, // 6: shahcoin.treasury.v1.Query.PolicyRate:output_type -> shahcoin.treasury.v1.QueryPolicyRateResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shahcoin_treasury_v1_query_proto_init() }
func file_shahcoin_treasury_v1_query_proto_init() {
	if File_shahcoin_treasury_v1_query_proto != nil {
		return
	}
	file_shahcoin_treasury_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_treasury_v1_query_proto_rawDesc), len(file_shahcoin_treasury_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shahcoin_treasury_v1_query_proto_goTypes,
		DependencyIndexes: file_shahcoin_treasury_v1_query_proto_depIdxs,
		MessageInfos:      file_shahcoin_treasury_v1_query_proto_msgTypes,
	}.Build()
	File_shahcoin_treasury_v1_query_proto = out.File
	file_shahcoin_treasury_v1_query_proto_goTypes = nil
	file_shahcoin_treasury_v1_query_proto_depIdxs = nil
}
