// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/treasury/v1/tx.proto

package types

import (
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgMintShahUSD mints SHAHUSD
type MsgMintShahUSD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Recipient     string                 `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgMintShahUSD) Reset() {
	*x = MsgMintShahUSD{}
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgMintShahUSD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMintShahUSD) ProtoMessage() {}

func (x *MsgMintShahUSD) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMintShahUSD.ProtoReflect.Descriptor instead.
func (*MsgMintShahUSD) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgMintShahUSD) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgMintShahUSD) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *MsgMintShahUSD) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MsgMintShahUSDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgMintShahUSDResponse) Reset() {
	*x = MsgMintShahUSDResponse{}
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgMintShahUSDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgMintShahUSDResponse) ProtoMessage() {}

func (x *MsgMintShahUSDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgMintShahUSDResponse.ProtoReflect.Descriptor instead.
func (*MsgMintShahUSDResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_tx_proto_rawDescGZIP(), []int{1}
}

// MsgBurnShahUSD burns SHAHUSD
type MsgBurnShahUSD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBurnShahUSD) Reset() {
	*x = MsgBurnShahUSD{}
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBurnShahUSD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBurnShahUSD) ProtoMessage() {}

func (x *MsgBurnShahUSD) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBurnShahUSD.ProtoReflect.Descriptor instead.
func (*MsgBurnShahUSD) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgBurnShahUSD) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgBurnShahUSD) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type MsgBurnShahUSDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBurnShahUSDResponse) Reset() {
	*x = MsgBurnShahUSDResponse{}
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBurnShahUSDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBurnShahUSDResponse) ProtoMessage() {}

func (x *MsgBurnShahUSDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBurnShahUSDResponse.ProtoReflect.Descriptor instead.
func (*MsgBurnShahUSDResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_tx_proto_rawDescGZIP(), []int{3}
}

// MsgBuyShah buys SHAH from treasury
type MsgBuyShah struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buyer         string                 `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	ShahusdIn     *types.Coin            `protobuf:"bytes,2,opt,name=shahusd_in,json=shahusdIn,proto3" json:"shahusd_in,omitempty"`
	MinShahOut    string                 `protobuf:"bytes,3,opt,name=min_shah_out,json=minShahOut,proto3" json:"min_shah_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBuyShah) Reset() {
	*x = MsgBuyShah{}
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBuyShah) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBuyShah) ProtoMessage() {}

func (x *MsgBuyShah) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBuyShah.ProtoReflect.Descriptor instead.
func (*MsgBuyShah) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgBuyShah) GetBuyer() string {
	if x != nil {
		return x.Buyer
	}
	return ""
}

func (x *MsgBuyShah) GetShahusdIn() *types.Coin {
	if x != nil {
		return x.ShahusdIn
	}
	return nil
}

func (x *MsgBuyShah) GetMinShahOut() string {
	if x != nil {
		return x.MinShahOut
	}
	return ""
}

type MsgBuyShahResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShahOut       *types.Coin            `protobuf:"bytes,1,opt,name=shah_out,json=shahOut,proto3" json:"shah_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBuyShahResponse) Reset() {
	*x = MsgBuyShahResponse{}
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBuyShahResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBuyShahResponse) ProtoMessage() {}

func (x *MsgBuyShahResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBuyShahResponse.ProtoReflect.Descriptor instead.
func (*MsgBuyShahResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MsgBuyShahResponse) GetShahOut() *types.Coin {
	if x != nil {
		return x.ShahOut
	}
	return nil
}

// MsgSellShah sells SHAH to treasury
type MsgSellShah struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seller        string                 `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
	ShahIn        *types.Coin            `protobuf:"bytes,2,opt,name=shah_in,json=shahIn,proto3" json:"shah_in,omitempty"`
	MinShahusdOut string                 `protobuf:"bytes,3,opt,name=min_shahusd_out,json=minShahusdOut,proto3" json:"min_shahusd_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSellShah) Reset() {
	*x = MsgSellShah{}
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSellShah) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSellShah) ProtoMessage() {}

func (x *MsgSellShah) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSellShah.ProtoReflect.Descriptor instead.
func (*MsgSellShah) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgSellShah) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *MsgSellShah) GetShahIn() *types.Coin {
	if x != nil {
		return x.ShahIn
	}
	return nil
}

func (x *MsgSellShah) GetMinShahusdOut() string {
	if x != nil {
		return x.MinShahusdOut
	}
	return ""
}

type MsgSellShahResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShahusdOut    *types.Coin            `protobuf:"bytes,1,opt,name=shahusd_out,json=shahusdOut,proto3" json:"shahusd_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSellShahResponse) Reset() {
	*x = MsgSellShahResponse{}
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSellShahResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSellShahResponse) ProtoMessage() {}

func (x *MsgSellShahResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSellShahResponse.ProtoReflect.Descriptor instead.
func (*MsgSellShahResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_tx_proto_rawDescGZIP(), []int{7}
}

func (x *MsgSellShahResponse) GetShahusdOut() *types.Coin {
	if x != nil {
		return x.ShahusdOut
	}
	return nil
}

// MsgUpdateParams updates params
type MsgUpdateParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params        *Params                `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_treasury_v1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_treasury_v1_tx_proto_rawDescGZIP(), []int{9}
}

var File_shahcoin_treasury_v1_tx_proto protoreflect.FileDescriptor

const file_shahcoin_treasury_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x1dshahcoin/treasury/v1/tx.proto\x12\x14shahcoin.treasury.v1\x1a\x1ecosmos/base/v1beta1/coin.proto\x1a\x17cosmos/msg/v1/msg.proto\x1a\x14gogoproto/gogo.proto\x1a!shahcoin/treasury/v1/params.proto\"\x93\x01\n" +
	"\x0eMsgMintShahUSD\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x125\n" +
	"\x06amount\x18\x03 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\x06amount:\x0e\x82\xe7\xb0*\tauthority\"\x18\n" +
	"\x16MsgMintShahUSDResponse\"l\n" +
	"\x0eMsgBurnShahUSD\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x125\n" +
	"\x06amount\x18\x02 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\x06amount:\v\x82\xe7\xb0*\x06sender\"\x18\n" +
	"\x16MsgBurnShahUSDResponse\"\xaf\x01\n" +
	"\n" +
	"MsgBuyShah\x12\x14\n" +
	"\x05buyer\x18\x01 \x01(\tR\x05buyer\x12>\n" +
	"\n" +
	"shahusd_in\x18\x02 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\tshahusdIn\x12?\n" +
	"\fmin_shah_out\x18\x03 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\n" +
	"minShahOut:\n" +
	"\x82\xe7\xb0*\x05buyer\"P\n" +
	"\x12MsgBuyShahResponse\x12:\n" +
	"\bshah_out\x18\x01 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\ashahOut\"\xb3\x01\n" +
	"\vMsgSellShah\x12\x16\n" +
	"\x06seller\x18\x01 \x01(\tR\x06seller\x128\n" +
	"\ashah_in\x18\x02 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x06shahIn\x12E\n" +
	"\x0fmin_shahusd_out\x18\x03 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\rminShahusdOut:\v\x82\xe7\xb0*\x06seller\"W\n" +
	"\x13MsgSellShahResponse\x12@\n" +
	"\vshahusd_out\x18\x01 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\n" +
	"shahusdOut\"{\n" +
	"\x0fMsgUpdateParams\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12:\n" +
	"\x06params\x18\x02 \x01(\v2\x1c.shahcoin.treasury.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params:\x0e\x82\xe7\xb0*\tauthority\"\x19\n" +
	"\x17MsgUpdateParamsResponse2\xe9\x03\n" +
	"\x03Msg\x12a\n" +
	"\vMintShahUSD\x12$.shahcoin.treasury.v1.MsgMintShahUSD\x1a,.shahcoin.treasury.v1.MsgMintShahUSDResponse\x12a\n" +
	"\vBurnShahUSD\x12$.shahcoin.treasury.v1.MsgBurnShahUSD\x1a,.shahcoin.treasury.v1.MsgBurnShahUSDResponse\x12U\n" +
	"\aBuyShah\x12 .shahcoin.treasury.v1.MsgBuyShah\x1a(.shahcoin.treasury.v1.MsgBuyShahResponse\x12X\n" +
	"\bSellShah\x12!.shahcoin.treasury.v1.MsgSellShah\x1a).shahcoin.treasury.v1.MsgSellShahResponse\x12d\n" +
	"\fUpdateParams\x12%.shahcoin.treasury.v1.MsgUpdateParams\x1a-.shahcoin.treasury.v1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01B/Z-github.com/shahcoin/shahcoin/x/treasury/typesb\x06proto3"

var (
	file_shahcoin_treasury_v1_tx_proto_rawDescOnce sync.Once
	file_shahcoin_treasury_v1_tx_proto_rawDescData []byte
)

func file_shahcoin_treasury_v1_tx_proto_rawDescGZIP() []byte {
	file_shahcoin_treasury_v1_tx_proto_rawDescOnce.Do(func() {
		file_shahcoin_treasury_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_treasury_v1_tx_proto_rawDesc), len(file_shahcoin_treasury_v1_tx_proto_rawDesc)))
	})
	return file_shahcoin_treasury_v1_tx_proto_rawDescData
}

var file_shahcoin_treasury_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_shahcoin_treasury_v1_tx_proto_goTypes = []any{
	(*MsgMintShahUSD)(nil),          // 0: shahcoin.treasury.v1.MsgMintShahUSD
	(*MsgMintShahUSDResponse)(nil),  // 1: shahcoin.treasury.v1.MsgMintShahUSDResponse
	(*MsgBurnShahUSD)(nil),          // 2: shahcoin.treasury.v1.MsgBurnShahUSD
	(*MsgBurnShahUSDResponse)(nil),  // 3: shahcoin.treasury.v1.MsgBurnShahUSDResponse
	(*MsgBuyShah)(nil),              // 4: shahcoin.treasury.v1.MsgBuyShah
	(*MsgBuyShahResponse)(nil),      // 5: shahcoin.treasury.v1.MsgBuyShahResponse
	(*MsgSellShah)(nil),             // 6: shahcoin.treasury.v1.MsgSellShah
	(*MsgSellShahResponse)(nil),     // 7: shahcoin.treasury.v1.MsgSellShahResponse
	(*MsgUpdateParams)(nil),         // 8: shahcoin.treasury.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil), // 9: shahcoin.treasury.v1.MsgUpdateParamsResponse
	(*types.Coin)(nil),              // 10: cosmos.base.v1beta1.Coin
	(*Params)(nil),                  // 11: shahcoin.treasury.v1.Params
}
var file_shahcoin_treasury_v1_tx_proto_depIdxs = []int32{
	10, // 0: shahcoin.treasury.v1.MsgBuyShah.shahusd_in:type_name -> cosmos.base.v1beta1.Coin
	10, // 1: shahcoin.treasury.v1.MsgBuyShahResponse.shah_out:type_name -> cosmos.base.v1beta1.Coin
	10, // 2: shahcoin.treasury.v1.MsgSellShah.shah_in:type_name -> cosmos.base.v1beta1.Coin
	10, // 3: shahcoin.treasury.v1.MsgSellShahResponse.shahusd_out:type_name -> cosmos.base.v1beta1.Coin
	11, // 4: shahcoin.treasury.v1.MsgUpdateParams.params:type_name -> shahcoin.treasury.v1.Params
	0,  // 5: shahcoin.treasury.v1.Msg.MintShahUSD:input_type -> shahcoin.treasury.v1.MsgMintShahUSD
	2,  // 6: shahcoin.treasury.v1.Msg.BurnShahUSD:input_type -> shahcoin.treasury.v1.MsgBurnShahUSD
	4,  // 7: shahcoin.treasury.v1.Msg.BuyShah:input_type -> shahcoin.treasury.v1.MsgBuyShah
	6,  // 8: shahcoin.treasury.v1.Msg.SellShah:input_type -> shahcoin.treasury.v1.MsgSellShah
	8,  // 9: shahcoin.treasury.v1.Msg.UpdateParams:input_type -> shahcoin.treasury.v1.MsgUpdateParams
	1,  // 10: shahcoin.treasury.v1.Msg.MintShahUSD:output_type -> shahcoin.treasury.v1.MsgMintShahUSDResponse
	3,  // 11: shahcoin.treasury.v1.Msg.BurnShahUSD:output_type -> shahcoin.treasury.v1.MsgBurnShahUSDResponse
	5,  // 12: shahcoin.treasury.v1.Msg.BuyShah:output_type -> shahcoin.treasury.v1.MsgBuyShahResponse
	7,  // 13: shahcoin.treasury.v1.Msg.SellShah:output_type -> shahcoin.treasury.v1.MsgSellShahResponse
	9,  // 14: shahcoin.treasury.v1.Msg.UpdateParams:output_type -> shahcoin.treasury.v1.MsgUpdateParamsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_shahcoin_treasury_v1_tx_proto_init() }
func file_shahcoin_treasury_v1_tx_proto_init() {
	if File_shahcoin_treasury_v1_tx_proto != nil {
		return
	}
	file_shahcoin_treasury_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_treasury_v1_tx_proto_rawDesc), len(file_shahcoin_treasury_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shahcoin_treasury_v1_tx_proto_goTypes,
		DependencyIndexes: file_shahcoin_treasury_v1_tx_proto_depIdxs,
		MessageInfos:      file_shahcoin_treasury_v1_tx_proto_msgTypes,
	}.Build()
	File_shahcoin_treasury_v1_tx_proto = out.File
	file_shahcoin_treasury_v1_tx_proto_goTypes = nil
	file_shahcoin_treasury_v1_tx_proto_depIdxs = nil
}
