// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: shahcoin/treasury/v1/tx.proto

package types

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Msg_MintShahUSD_FullMethodName  = "/shahcoin.treasury.v1.Msg/MintShahUSD"
	Msg_BurnShahUSD_FullMethodName  = "/shahcoin.treasury.v1.Msg/BurnShahUSD"
	Msg_BuyShah_FullMethodName      = "/shahcoin.treasury.v1.Msg/BuyShah"
	Msg_SellShah_FullMethodName     = "/shahcoin.treasury.v1.Msg/SellShah"
	Msg_UpdateParams_FullMethodName = "/shahcoin.treasury.v1.Msg/UpdateParams"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Msg defines the treasury Msg service.
type MsgClient interface {
	// MintShahUSD mints SHAHUSD (admin/gov only)
	MintShahUSD(ctx context.Context, in *MsgMintShahUSD, opts ...grpc.CallOption) (*MsgMintShahUSDResponse, error)
	// BurnShahUSD burns SHAHUSD
	BurnShahUSD(ctx context.Context, in *MsgBurnShahUSD, opts ...grpc.CallOption) (*MsgBurnShahUSDResponse, error)
	// BuyShah buys SHAH from treasury with SHAHUSD
	BuyShah(ctx context.Context, in *MsgBuyShah, opts ...grpc.CallOption) (*MsgBuyShahResponse, error)
	// SellShah sells SHAH to treasury for SHAHUSD
	SellShah(ctx context.Context, in *MsgSellShah, opts ...grpc.CallOption) (*MsgSellShahResponse, error)
	// UpdateParams updates the module parameters (governance only)
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) MintShahUSD(ctx context.Context, in *MsgMintShahUSD, opts ...grpc.CallOption) (*MsgMintShahUSDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgMintShahUSDResponse)
	err := c.cc.Invoke(ctx, Msg_MintShahUSD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BurnShahUSD(ctx context.Context, in *MsgBurnShahUSD, opts ...grpc.CallOption) (*MsgBurnShahUSDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgBurnShahUSDResponse)
	err := c.cc.Invoke(ctx, Msg_BurnShahUSD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BuyShah(ctx context.Context, in *MsgBuyShah, opts ...grpc.CallOption) (*MsgBuyShahResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgBuyShahResponse)
	err := c.cc.Invoke(ctx, Msg_BuyShah_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SellShah(ctx context.Context, in *MsgSellShah, opts ...grpc.CallOption) (*MsgSellShahResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgSellShahResponse)
	err := c.cc.Invoke(ctx, Msg_SellShah_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility.
//
// Msg defines the treasury Msg service.
type MsgServer interface {
	// MintShahUSD mints SHAHUSD (admin/gov only)
	MintShahUSD(context.Context, *MsgMintShahUSD) (*MsgMintShahUSDResponse, error)
	// BurnShahUSD burns SHAHUSD
	BurnShahUSD(context.Context, *MsgBurnShahUSD) (*MsgBurnShahUSDResponse, error)
	// BuyShah buys SHAH from treasury with SHAHUSD
	BuyShah(context.Context, *MsgBuyShah) (*MsgBuyShahResponse, error)
	// SellShah sells SHAH to treasury for SHAHUSD
	SellShah(context.Context, *MsgSellShah) (*MsgSellShahResponse, error)
	// UpdateParams updates the module parameters (governance only)
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServer struct{}

func (UnimplementedMsgServer) MintShahUSD(context.Context, *MsgMintShahUSD) (*MsgMintShahUSDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintShahUSD not implemented")
}
func (UnimplementedMsgServer) BurnShahUSD(context.Context, *MsgBurnShahUSD) (*MsgBurnShahUSDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BurnShahUSD not implemented")
}
func (UnimplementedMsgServer) BuyShah(context.Context, *MsgBuyShah) (*MsgBuyShahResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyShah not implemented")
}
func (UnimplementedMsgServer) SellShah(context.Context, *MsgSellShah) (*MsgSellShahResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellShah not implemented")
}
func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}
func (UnimplementedMsgServer) testEmbeddedByValue()             {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	// If the following call pancis, it indicates UnimplementedMsgServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_MintShahUSD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMintShahUSD)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MintShahUSD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_MintShahUSD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MintShahUSD(ctx, req.(*MsgMintShahUSD))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BurnShahUSD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBurnShahUSD)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BurnShahUSD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_BurnShahUSD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BurnShahUSD(ctx, req.(*MsgBurnShahUSD))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BuyShah_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBuyShah)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BuyShah(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_BuyShah_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BuyShah(ctx, req.(*MsgBuyShah))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SellShah_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSellShah)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SellShah(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_SellShah_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SellShah(ctx, req.(*MsgSellShah))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shahcoin.treasury.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MintShahUSD",
			Handler:    _Msg_MintShahUSD_Handler,
		},
		{
			MethodName: "BurnShahUSD",
			Handler:    _Msg_BurnShahUSD_Handler,
		},
		{
			MethodName: "BuyShah",
			Handler:    _Msg_BuyShah_Handler,
		},
		{
			MethodName: "SellShah",
			Handler:    _Msg_SellShah_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shahcoin/treasury/v1/tx.proto",
}
