// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/airdrop/v1/genesis.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenesisState defines the airdrop module's genesis state.
type GenesisState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// params defines all the parameters of the module.
	Params *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	// merkle_root is the root of the Merkle tree for claims
	MerkleRoot string `protobuf:"bytes,2,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	// claimed is a map of addresses that have claimed (stored as list)
	ClaimedAddresses []string `protobuf:"bytes,3,rep,name=claimed_addresses,json=claimedAddresses,proto3" json:"claimed_addresses,omitempty"`
	// start_time is when claims can begin
	StartTime int64 `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// end_time is when claims end
	EndTime       int64 `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_shahcoin_airdrop_v1_genesis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_airdrop_v1_genesis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_shahcoin_airdrop_v1_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *GenesisState) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenesisState) GetMerkleRoot() string {
	if x != nil {
		return x.MerkleRoot
	}
	return ""
}

func (x *GenesisState) GetClaimedAddresses() []string {
	if x != nil {
		return x.ClaimedAddresses
	}
	return nil
}

func (x *GenesisState) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GenesisState) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

var File_shahcoin_airdrop_v1_genesis_proto protoreflect.FileDescriptor

const file_shahcoin_airdrop_v1_genesis_proto_rawDesc = "" +
	"\n" +
	"!shahcoin/airdrop/v1/genesis.proto\x12\x13shahcoin.airdrop.v1\x1a\x14gogoproto/gogo.proto\x1a shahcoin/airdrop/v1/params.proto\"\xd1\x01\n" +
	"\fGenesisState\x129\n" +
	"\x06params\x18\x01 \x01(\v2\x1b.shahcoin.airdrop.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\x12\x1f\n" +
	"\vmerkle_root\x18\x02 \x01(\tR\n" +
	"merkleRoot\x12+\n" +
	"\x11claimed_addresses\x18\x03 \x03(\tR\x10claimedAddresses\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTimeB.Z,github.com/shahcoin/shahcoin/x/airdrop/typesb\x06proto3"

var (
	file_shahcoin_airdrop_v1_genesis_proto_rawDescOnce sync.Once
	file_shahcoin_airdrop_v1_genesis_proto_rawDescData []byte
)

func file_shahcoin_airdrop_v1_genesis_proto_rawDescGZIP() []byte {
	file_shahcoin_airdrop_v1_genesis_proto_rawDescOnce.Do(func() {
		file_shahcoin_airdrop_v1_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_airdrop_v1_genesis_proto_rawDesc), len(file_shahcoin_airdrop_v1_genesis_proto_rawDesc)))
	})
	return file_shahcoin_airdrop_v1_genesis_proto_rawDescData
}

var file_shahcoin_airdrop_v1_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shahcoin_airdrop_v1_genesis_proto_goTypes = []any{
	(*GenesisState)(nil), // 0: shahcoin.airdrop.v1.GenesisState
	(*Params)(nil),       // 1: shahcoin.airdrop.v1.Params
}
var file_shahcoin_airdrop_v1_genesis_proto_depIdxs = []int32{
	1, // 0: shahcoin.airdrop.v1.GenesisState.params:type_name -> shahcoin.airdrop.v1.Params
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shahcoin_airdrop_v1_genesis_proto_init() }
func file_shahcoin_airdrop_v1_genesis_proto_init() {
	if File_shahcoin_airdrop_v1_genesis_proto != nil {
		return
	}
	file_shahcoin_airdrop_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_airdrop_v1_genesis_proto_rawDesc), len(file_shahcoin_airdrop_v1_genesis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shahcoin_airdrop_v1_genesis_proto_goTypes,
		DependencyIndexes: file_shahcoin_airdrop_v1_genesis_proto_depIdxs,
		MessageInfos:      file_shahcoin_airdrop_v1_genesis_proto_msgTypes,
	}.Build()
	File_shahcoin_airdrop_v1_genesis_proto = out.File
	file_shahcoin_airdrop_v1_genesis_proto_goTypes = nil
	file_shahcoin_airdrop_v1_genesis_proto_depIdxs = nil
}
