// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/airdrop/v1/params.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Params defines the parameters for the airdrop module.
type Params struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// airdrop_enabled controls whether claims are accepted
	AirdropEnabled bool `protobuf:"varint,1,opt,name=airdrop_enabled,json=airdropEnabled,proto3" json:"airdrop_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_shahcoin_airdrop_v1_params_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_airdrop_v1_params_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_shahcoin_airdrop_v1_params_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetAirdropEnabled() bool {
	if x != nil {
		return x.AirdropEnabled
	}
	return false
}

var File_shahcoin_airdrop_v1_params_proto protoreflect.FileDescriptor

const file_shahcoin_airdrop_v1_params_proto_rawDesc = "" +
	"\n" +
	" shahcoin/airdrop/v1/params.proto\x12\x13shahcoin.airdrop.v1\x1a\x14gogoproto/gogo.proto\"7\n" +
	"\x06Params\x12'\n" +
	"\x0fairdrop_enabled\x18\x01 \x01(\bR\x0eairdropEnabled:\x04\x98\xa0\x1f\x00B.Z,github.com/shahcoin/shahcoin/x/airdrop/typesb\x06proto3"

var (
	file_shahcoin_airdrop_v1_params_proto_rawDescOnce sync.Once
	file_shahcoin_airdrop_v1_params_proto_rawDescData []byte
)

func file_shahcoin_airdrop_v1_params_proto_rawDescGZIP() []byte {
	file_shahcoin_airdrop_v1_params_proto_rawDescOnce.Do(func() {
		file_shahcoin_airdrop_v1_params_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_airdrop_v1_params_proto_rawDesc), len(file_shahcoin_airdrop_v1_params_proto_rawDesc)))
	})
	return file_shahcoin_airdrop_v1_params_proto_rawDescData
}

var file_shahcoin_airdrop_v1_params_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shahcoin_airdrop_v1_params_proto_goTypes = []any{
	(*Params)(nil), // 0: shahcoin.airdrop.v1.Params
}
var file_shahcoin_airdrop_v1_params_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shahcoin_airdrop_v1_params_proto_init() }
func file_shahcoin_airdrop_v1_params_proto_init() {
	if File_shahcoin_airdrop_v1_params_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_airdrop_v1_params_proto_rawDesc), len(file_shahcoin_airdrop_v1_params_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shahcoin_airdrop_v1_params_proto_goTypes,
		DependencyIndexes: file_shahcoin_airdrop_v1_params_proto_depIdxs,
		MessageInfos:      file_shahcoin_airdrop_v1_params_proto_msgTypes,
	}.Build()
	File_shahcoin_airdrop_v1_params_proto = out.File
	file_shahcoin_airdrop_v1_params_proto_goTypes = nil
	file_shahcoin_airdrop_v1_params_proto_depIdxs = nil
}
