// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/airdrop/v1/query.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_shahcoin_airdrop_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_airdrop_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_airdrop_v1_query_proto_rawDescGZIP(), []int{0}
}

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_shahcoin_airdrop_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_airdrop_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_airdrop_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// QueryClaimStatusRequest is the request type for Query/ClaimStatus
type QueryClaimStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryClaimStatusRequest) Reset() {
	*x = QueryClaimStatusRequest{}
	mi := &file_shahcoin_airdrop_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryClaimStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryClaimStatusRequest) ProtoMessage() {}

func (x *QueryClaimStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_airdrop_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryClaimStatusRequest.ProtoReflect.Descriptor instead.
func (*QueryClaimStatusRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_airdrop_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryClaimStatusRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// QueryClaimStatusResponse is the response type for Query/ClaimStatus
type QueryClaimStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claimed       bool                   `protobuf:"varint,1,opt,name=claimed,proto3" json:"claimed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryClaimStatusResponse) Reset() {
	*x = QueryClaimStatusResponse{}
	mi := &file_shahcoin_airdrop_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryClaimStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryClaimStatusResponse) ProtoMessage() {}

func (x *QueryClaimStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_airdrop_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryClaimStatusResponse.ProtoReflect.Descriptor instead.
func (*QueryClaimStatusResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_airdrop_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryClaimStatusResponse) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

var File_shahcoin_airdrop_v1_query_proto protoreflect.FileDescriptor

const file_shahcoin_airdrop_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1fshahcoin/airdrop/v1/query.proto\x12\x13shahcoin.airdrop.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\x1a shahcoin/airdrop/v1/params.proto\"\x14\n" +
	"\x12QueryParamsRequest\"P\n" +
	"\x13QueryParamsResponse\x129\n" +
	"\x06params\x18\x01 \x01(\v2\x1b.shahcoin.airdrop.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\"3\n" +
	"\x17QueryClaimStatusRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"4\n" +
	"\x18QueryClaimStatusResponse\x12\x18\n" +
	"\aclaimed\x18\x01 \x01(\bR\aclaimed2\xac\x02\n" +
	"\x05Query\x12\x80\x01\n" +
	"\x06Params\x12'.shahcoin.airdrop.v1.QueryParamsRequest\x1a(.shahcoin.airdrop.v1.QueryParamsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/shahcoin/airdrop/v1/params\x12\x9f\x01\n" +
	"\vClaimStatus\x12,.shahcoin.airdrop.v1.QueryClaimStatusRequest\x1a-.shahcoin.airdrop.v1.QueryClaimStatusResponse\"3\x82\xd3\xe4\x93\x02-\x12+/shahcoin/airdrop/v1/claim_status/{address}B.Z,github.com/shahcoin/shahcoin/x/airdrop/typesb\x06proto3"

var (
	file_shahcoin_airdrop_v1_query_proto_rawDescOnce sync.Once
	file_shahcoin_airdrop_v1_query_proto_rawDescData []byte
)

func file_shahcoin_airdrop_v1_query_proto_rawDescGZIP() []byte {
	file_shahcoin_airdrop_v1_query_proto_rawDescOnce.Do(func() {
		file_shahcoin_airdrop_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_airdrop_v1_query_proto_rawDesc), len(file_shahcoin_airdrop_v1_query_proto_rawDesc)))
	})
	return file_shahcoin_airdrop_v1_query_proto_rawDescData
}

var file_shahcoin_airdrop_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shahcoin_airdrop_v1_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),       // 0: shahcoin.airdrop.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),      // 1: shahcoin.airdrop.v1.QueryParamsResponse
	(*QueryClaimStatusRequest)(nil),  // 2: shahcoin.airdrop.v1.QueryClaimStatusRequest
	(*QueryClaimStatusResponse)(nil), // 3: shahcoin.airdrop.v1.QueryClaimStatusResponse
	(*Params)(nil),                   // 4: shahcoin.airdrop.v1.Params
}
var file_shahcoin_airdrop_v1_query_proto_depIdxs = []int32{
	4, // 0: shahcoin.airdrop.v1.QueryParamsResponse.params:type_name -> shahcoin.airdrop.v1.Params
	0, // 1: shahcoin.airdrop.v1.Query.Params:input_type -> shahcoin.airdrop.v1.QueryParamsRequest
	2, // 2: shahcoin.airdrop.v1.Query.ClaimStatus:input_type -> shahcoin.airdrop.v1.QueryClaimStatusRequest
	1, // 3: shahcoin.airdrop.v1.Query.Params:output_type -> shahcoin.airdrop.v1.QueryParamsResponse
	3, // 4: shahcoin.airdrop.v1.Query.ClaimStatus:output_type -> shahcoin.airdrop.v1.QueryClaimStatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shahcoin_airdrop_v1_query_proto_init() }
func file_shahcoin_airdrop_v1_query_proto_init() {
	if File_shahcoin_airdrop_v1_query_proto != nil {
		return
	}
	file_shahcoin_airdrop_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_airdrop_v1_query_proto_rawDesc), len(file_shahcoin_airdrop_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shahcoin_airdrop_v1_query_proto_goTypes,
		DependencyIndexes: file_shahcoin_airdrop_v1_query_proto_depIdxs,
		MessageInfos:      file_shahcoin_airdrop_v1_query_proto_msgTypes,
	}.Build()
	File_shahcoin_airdrop_v1_query_proto = out.File
	file_shahcoin_airdrop_v1_query_proto_goTypes = nil
	file_shahcoin_airdrop_v1_query_proto_depIdxs = nil
}
