// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/airdrop/v1/tx.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgClaim claims airdrop tokens
type MsgClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claimer       string                 `protobuf:"bytes,1,opt,name=claimer,proto3" json:"claimer,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	MerkleProof   [][]byte               `protobuf:"bytes,3,rep,name=merkle_proof,json=merkleProof,proto3" json:"merkle_proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgClaim) Reset() {
	*x = MsgClaim{}
	mi := &file_shahcoin_airdrop_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgClaim) ProtoMessage() {}

func (x *MsgClaim) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_airdrop_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgClaim.ProtoReflect.Descriptor instead.
func (*MsgClaim) Descriptor() ([]byte, []int) {
	return file_shahcoin_airdrop_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgClaim) GetClaimer() string {
	if x != nil {
		return x.Claimer
	}
	return ""
}

func (x *MsgClaim) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MsgClaim) GetMerkleProof() [][]byte {
	if x != nil {
		return x.MerkleProof
	}
	return nil
}

type MsgClaimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountClaimed string                 `protobuf:"bytes,1,opt,name=amount_claimed,json=amountClaimed,proto3" json:"amount_claimed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgClaimResponse) Reset() {
	*x = MsgClaimResponse{}
	mi := &file_shahcoin_airdrop_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgClaimResponse) ProtoMessage() {}

func (x *MsgClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_airdrop_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgClaimResponse.ProtoReflect.Descriptor instead.
func (*MsgClaimResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_airdrop_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgClaimResponse) GetAmountClaimed() string {
	if x != nil {
		return x.AmountClaimed
	}
	return ""
}

// MsgUpdateParams updates params
type MsgUpdateParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params        *Params                `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_shahcoin_airdrop_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_airdrop_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_shahcoin_airdrop_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_shahcoin_airdrop_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_airdrop_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_airdrop_v1_tx_proto_rawDescGZIP(), []int{3}
}

var File_shahcoin_airdrop_v1_tx_proto protoreflect.FileDescriptor

const file_shahcoin_airdrop_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x1cshahcoin/airdrop/v1/tx.proto\x12\x13shahcoin.airdrop.v1\x1a\x17cosmos/msg/v1/msg.proto\x1a\x14gogoproto/gogo.proto\x1a shahcoin/airdrop/v1/params.proto\"\x8c\x01\n" +
	"\bMsgClaim\x12\x18\n" +
	"\aclaimer\x18\x01 \x01(\tR\aclaimer\x125\n" +
	"\x06amount\x18\x02 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\x06amount\x12!\n" +
	"\fmerkle_proof\x18\x03 \x03(\fR\vmerkleProof:\f\x82\xe7\xb0*\aclaimer\"X\n" +
	"\x10MsgClaimResponse\x12D\n" +
	"\x0eamount_claimed\x18\x01 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\ramountClaimed\"z\n" +
	"\x0fMsgUpdateParams\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x129\n" +
	"\x06params\x18\x02 \x01(\v2\x1b.shahcoin.airdrop.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params:\x0e\x82\xe7\xb0*\tauthority\"\x19\n" +
	"\x17MsgUpdateParamsResponse2\xbf\x01\n" +
	"\x03Msg\x12M\n" +
	"\x05Claim\x12\x1d.shahcoin.airdrop.v1.MsgClaim\x1a%.shahcoin.airdrop.v1.MsgClaimResponse\x12b\n" +
	"\fUpdateParams\x12$.shahcoin.airdrop.v1.MsgUpdateParams\x1a,.shahcoin.airdrop.v1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01B.Z,github.com/shahcoin/shahcoin/x/airdrop/typesb\x06proto3"

var (
	file_shahcoin_airdrop_v1_tx_proto_rawDescOnce sync.Once
	file_shahcoin_airdrop_v1_tx_proto_rawDescData []byte
)

func file_shahcoin_airdrop_v1_tx_proto_rawDescGZIP() []byte {
	file_shahcoin_airdrop_v1_tx_proto_rawDescOnce.Do(func() {
		file_shahcoin_airdrop_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_airdrop_v1_tx_proto_rawDesc), len(file_shahcoin_airdrop_v1_tx_proto_rawDesc)))
	})
	return file_shahcoin_airdrop_v1_tx_proto_rawDescData
}

var file_shahcoin_airdrop_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shahcoin_airdrop_v1_tx_proto_goTypes = []any{
	(*MsgClaim)(nil),                // 0: shahcoin.airdrop.v1.MsgClaim
	(*MsgClaimResponse)(nil),        // 1: shahcoin.airdrop.v1.MsgClaimResponse
	(*MsgUpdateParams)(nil),         // 2: shahcoin.airdrop.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil), // 3: shahcoin.airdrop.v1.MsgUpdateParamsResponse
	(*Params)(nil),                  // 4: shahcoin.airdrop.v1.Params
}
var file_shahcoin_airdrop_v1_tx_proto_depIdxs = []int32{
	4, // 0: shahcoin.airdrop.v1.MsgUpdateParams.params:type_name -> shahcoin.airdrop.v1.Params
	0, // 1: shahcoin.airdrop.v1.Msg.Claim:input_type -> shahcoin.airdrop.v1.MsgClaim
	2, // 2: shahcoin.airdrop.v1.Msg.UpdateParams:input_type -> shahcoin.airdrop.v1.MsgUpdateParams
	1, // 3: shahcoin.airdrop.v1.Msg.Claim:output_type -> shahcoin.airdrop.v1.MsgClaimResponse
	3, // 4: shahcoin.airdrop.v1.Msg.UpdateParams:output_type -> shahcoin.airdrop.v1.MsgUpdateParamsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shahcoin_airdrop_v1_tx_proto_init() }
func file_shahcoin_airdrop_v1_tx_proto_init() {
	if File_shahcoin_airdrop_v1_tx_proto != nil {
		return
	}
	file_shahcoin_airdrop_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_airdrop_v1_tx_proto_rawDesc), len(file_shahcoin_airdrop_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shahcoin_airdrop_v1_tx_proto_goTypes,
		DependencyIndexes: file_shahcoin_airdrop_v1_tx_proto_depIdxs,
		MessageInfos:      file_shahcoin_airdrop_v1_tx_proto_msgTypes,
	}.Build()
	File_shahcoin_airdrop_v1_tx_proto = out.File
	file_shahcoin_airdrop_v1_tx_proto_goTypes = nil
	file_shahcoin_airdrop_v1_tx_proto_depIdxs = nil
}
