// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/shahswap/v1/genesis.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenesisState defines the shahswap module's genesis state.
type GenesisState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// params defines all the parameters of the module.
	Params *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	// pools defines all the liquidity pools
	Pools []*Pool `protobuf:"bytes,2,rep,name=pools,proto3" json:"pools,omitempty"`
	// pool_counter is the next pool ID to be assigned
	PoolCounter   uint64 `protobuf:"varint,3,opt,name=pool_counter,json=poolCounter,proto3" json:"pool_counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_shahcoin_shahswap_v1_genesis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_genesis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *GenesisState) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenesisState) GetPools() []*Pool {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *GenesisState) GetPoolCounter() uint64 {
	if x != nil {
		return x.PoolCounter
	}
	return 0
}

var File_shahcoin_shahswap_v1_genesis_proto protoreflect.FileDescriptor

const file_shahcoin_shahswap_v1_genesis_proto_rawDesc = "" +
	"\n" +
	"\"shahcoin/shahswap/v1/genesis.proto\x12\x14shahcoin.shahswap.v1\x1a\x14gogoproto/gogo.proto\x1a!shahcoin/shahswap/v1/params.proto\x1a\x1fshahcoin/shahswap/v1/pool.proto\"\xa5\x01\n" +
	"\fGenesisState\x12:\n" +
	"\x06params\x18\x01 \x01(\v2\x1c.shahcoin.shahswap.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\x126\n" +
	"\x05pools\x18\x02 \x03(\v2\x1a.shahcoin.shahswap.v1.PoolB\x04\xc8\xde\x1f\x00R\x05pools\x12!\n" +
	"\fpool_counter\x18\x03 \x01(\x04R\vpoolCounterB/Z-github.com/shahcoin/shahcoin/x/shahswap/typesb\x06proto3"

var (
	file_shahcoin_shahswap_v1_genesis_proto_rawDescOnce sync.Once
	file_shahcoin_shahswap_v1_genesis_proto_rawDescData []byte
)

func file_shahcoin_shahswap_v1_genesis_proto_rawDescGZIP() []byte {
	file_shahcoin_shahswap_v1_genesis_proto_rawDescOnce.Do(func() {
		file_shahcoin_shahswap_v1_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_shahswap_v1_genesis_proto_rawDesc), len(file_shahcoin_shahswap_v1_genesis_proto_rawDesc)))
	})
	return file_shahcoin_shahswap_v1_genesis_proto_rawDescData
}

var file_shahcoin_shahswap_v1_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shahcoin_shahswap_v1_genesis_proto_goTypes = []any{
	(*GenesisState)(nil), // 0: shahcoin.shahswap.v1.GenesisState
	(*Params)(nil),       // 1: shahcoin.shahswap.v1.Params
	(*Pool)(nil),         // 2: shahcoin.shahswap.v1.Pool
}
var file_shahcoin_shahswap_v1_genesis_proto_depIdxs = []int32{
	1, // 0: shahcoin.shahswap.v1.GenesisState.params:type_name -> shahcoin.shahswap.v1.Params
	2, // 1: shahcoin.shahswap.v1.GenesisState.pools:type_name -> shahcoin.shahswap.v1.Pool
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shahcoin_shahswap_v1_genesis_proto_init() }
func file_shahcoin_shahswap_v1_genesis_proto_init() {
	if File_shahcoin_shahswap_v1_genesis_proto != nil {
		return
	}
	file_shahcoin_shahswap_v1_params_proto_init()
	file_shahcoin_shahswap_v1_pool_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_shahswap_v1_genesis_proto_rawDesc), len(file_shahcoin_shahswap_v1_genesis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shahcoin_shahswap_v1_genesis_proto_goTypes,
		DependencyIndexes: file_shahcoin_shahswap_v1_genesis_proto_depIdxs,
		MessageInfos:      file_shahcoin_shahswap_v1_genesis_proto_msgTypes,
	}.Build()
	File_shahcoin_shahswap_v1_genesis_proto = out.File
	file_shahcoin_shahswap_v1_genesis_proto_goTypes = nil
	file_shahcoin_shahswap_v1_genesis_proto_depIdxs = nil
}
