// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/shahswap/v1/query.proto

package types

import (
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_query_proto_rawDescGZIP(), []int{0}
}

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// QueryPoolRequest is request type for Query/Pool RPC method
type QueryPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        uint64                 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPoolRequest) Reset() {
	*x = QueryPoolRequest{}
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPoolRequest) ProtoMessage() {}

func (x *QueryPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPoolRequest.ProtoReflect.Descriptor instead.
func (*QueryPoolRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryPoolRequest) GetPoolId() uint64 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

// QueryPoolResponse is response type for Query/Pool RPC method
type QueryPoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pool          *Pool                  `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPoolResponse) Reset() {
	*x = QueryPoolResponse{}
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPoolResponse) ProtoMessage() {}

func (x *QueryPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPoolResponse.ProtoReflect.Descriptor instead.
func (*QueryPoolResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryPoolResponse) GetPool() *Pool {
	if x != nil {
		return x.Pool
	}
	return nil
}

// QueryPoolsRequest is request type for Query/Pools RPC method
type QueryPoolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *query.PageRequest     `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPoolsRequest) Reset() {
	*x = QueryPoolsRequest{}
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPoolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPoolsRequest) ProtoMessage() {}

func (x *QueryPoolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPoolsRequest.ProtoReflect.Descriptor instead.
func (*QueryPoolsRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryPoolsRequest) GetPagination() *query.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QueryPoolsResponse is response type for Query/Pools RPC method
type QueryPoolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pools         []*Pool                `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"`
	Pagination    *query.PageResponse    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPoolsResponse) Reset() {
	*x = QueryPoolsResponse{}
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPoolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPoolsResponse) ProtoMessage() {}

func (x *QueryPoolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPoolsResponse.ProtoReflect.Descriptor instead.
func (*QueryPoolsResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryPoolsResponse) GetPools() []*Pool {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *QueryPoolsResponse) GetPagination() *query.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QuerySpotPriceRequest is request for spot price
type QuerySpotPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        uint64                 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	DenomIn       string                 `protobuf:"bytes,2,opt,name=denom_in,json=denomIn,proto3" json:"denom_in,omitempty"`
	DenomOut      string                 `protobuf:"bytes,3,opt,name=denom_out,json=denomOut,proto3" json:"denom_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySpotPriceRequest) Reset() {
	*x = QuerySpotPriceRequest{}
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySpotPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySpotPriceRequest) ProtoMessage() {}

func (x *QuerySpotPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySpotPriceRequest.ProtoReflect.Descriptor instead.
func (*QuerySpotPriceRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *QuerySpotPriceRequest) GetPoolId() uint64 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *QuerySpotPriceRequest) GetDenomIn() string {
	if x != nil {
		return x.DenomIn
	}
	return ""
}

func (x *QuerySpotPriceRequest) GetDenomOut() string {
	if x != nil {
		return x.DenomOut
	}
	return ""
}

// QuerySpotPriceResponse is response for spot price
type QuerySpotPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpotPrice     string                 `protobuf:"bytes,1,opt,name=spot_price,json=spotPrice,proto3" json:"spot_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuerySpotPriceResponse) Reset() {
	*x = QuerySpotPriceResponse{}
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuerySpotPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuerySpotPriceResponse) ProtoMessage() {}

func (x *QuerySpotPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuerySpotPriceResponse.ProtoReflect.Descriptor instead.
func (*QuerySpotPriceResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QuerySpotPriceResponse) GetSpotPrice() string {
	if x != nil {
		return x.SpotPrice
	}
	return ""
}

// QueryLPPositionRequest is request for LP position
type QueryLPPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        uint64                 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLPPositionRequest) Reset() {
	*x = QueryLPPositionRequest{}
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLPPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLPPositionRequest) ProtoMessage() {}

func (x *QueryLPPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLPPositionRequest.ProtoReflect.Descriptor instead.
func (*QueryLPPositionRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryLPPositionRequest) GetPoolId() uint64 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *QueryLPPositionRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// QueryLPPositionResponse is response for LP position
type QueryLPPositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *LPPosition            `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryLPPositionResponse) Reset() {
	*x = QueryLPPositionResponse{}
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLPPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLPPositionResponse) ProtoMessage() {}

func (x *QueryLPPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLPPositionResponse.ProtoReflect.Descriptor instead.
func (*QueryLPPositionResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryLPPositionResponse) GetPosition() *LPPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

var File_shahcoin_shahswap_v1_query_proto protoreflect.FileDescriptor

const file_shahcoin_shahswap_v1_query_proto_rawDesc = "" +
	"\n" +
	" shahcoin/shahswap/v1/query.proto\x12\x14shahcoin.shahswap.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\x1a!shahcoin/shahswap/v1/params.proto\x1a\x1fshahcoin/shahswap/v1/pool.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\"\x14\n" +
	"\x12QueryParamsRequest\"Q\n" +
	"\x13QueryParamsResponse\x12:\n" +
	"\x06params\x18\x01 \x01(\v2\x1c.shahcoin.shahswap.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\"+\n" +
	"\x10QueryPoolRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\x04R\x06poolId\"I\n" +
	"\x11QueryPoolResponse\x124\n" +
	"\x04pool\x18\x01 \x01(\v2\x1a.shahcoin.shahswap.v1.PoolB\x04\xc8\xde\x1f\x00R\x04pool\"[\n" +
	"\x11QueryPoolsRequest\x12F\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\x95\x01\n" +
	"\x12QueryPoolsResponse\x126\n" +
	"\x05pools\x18\x01 \x03(\v2\x1a.shahcoin.shahswap.v1.PoolB\x04\xc8\xde\x1f\x00R\x05pools\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\"h\n" +
	"\x15QuerySpotPriceRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\x04R\x06poolId\x12\x19\n" +
	"\bdenom_in\x18\x02 \x01(\tR\adenomIn\x12\x1b\n" +
	"\tdenom_out\x18\x03 \x01(\tR\bdenomOut\"\\\n" +
	"\x16QuerySpotPriceResponse\x12B\n" +
	"\n" +
	"spot_price\x18\x01 \x01(\tB#\xc8\xde\x1f\x00\xda\xde\x1f\x1bcosmossdk.io/math.LegacyDecR\tspotPrice\"K\n" +
	"\x16QueryLPPositionRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\x04R\x06poolId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"]\n" +
	"\x17QueryLPPositionResponse\x12B\n" +
	"\bposition\x18\x01 \x01(\v2 .shahcoin.shahswap.v1.LPPositionB\x04\xc8\xde\x1f\x00R\bposition2\xdf\x05\n" +
	"\x05Query\x12\x83\x01\n" +
	"\x06Params\x12(.shahcoin.shahswap.v1.QueryParamsRequest\x1a).shahcoin.shahswap.v1.QueryParamsResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/shahcoin/shahswap/v1/params\x12\x86\x01\n" +
	"\x04Pool\x12&.shahcoin.shahswap.v1.QueryPoolRequest\x1a'.shahcoin.shahswap.v1.QueryPoolResponse\"-\x82\xd3\xe4\x93\x02'\x12%/shahcoin/shahswap/v1/pools/{pool_id}\x12\x7f\n" +
	"\x05Pools\x12'.shahcoin.shahswap.v1.QueryPoolsRequest\x1a(.shahcoin.shahswap.v1.QueryPoolsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/shahcoin/shahswap/v1/pools\x12\x9a\x01\n" +
	"\tSpotPrice\x12+.shahcoin.shahswap.v1.QuerySpotPriceRequest\x1a,.shahcoin.shahswap.v1.QuerySpotPriceResponse\"2\x82\xd3\xe4\x93\x02,\x12*/shahcoin/shahswap/v1/spot_price/{pool_id}\x12\xa8\x01\n" +
	"\n" +
	"LPPosition\x12,.shahcoin.shahswap.v1.QueryLPPositionRequest\x1a-.shahcoin.shahswap.v1.QueryLPPositionResponse\"=\x82\xd3\xe4\x93\x027\x125/shahcoin/shahswap/v1/lp_position/{pool_id}/{address}B/Z-github.com/shahcoin/shahcoin/x/shahswap/typesb\x06proto3"

var (
	file_shahcoin_shahswap_v1_query_proto_rawDescOnce sync.Once
	file_shahcoin_shahswap_v1_query_proto_rawDescData []byte
)

func file_shahcoin_shahswap_v1_query_proto_rawDescGZIP() []byte {
	file_shahcoin_shahswap_v1_query_proto_rawDescOnce.Do(func() {
		file_shahcoin_shahswap_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_shahswap_v1_query_proto_rawDesc), len(file_shahcoin_shahswap_v1_query_proto_rawDesc)))
	})
	return file_shahcoin_shahswap_v1_query_proto_rawDescData
}

var file_shahcoin_shahswap_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_shahcoin_shahswap_v1_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),      // 0: shahcoin.shahswap.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),     // 1: shahcoin.shahswap.v1.QueryParamsResponse
	(*QueryPoolRequest)(nil),        // 2: shahcoin.shahswap.v1.QueryPoolRequest
	(*QueryPoolResponse)(nil),       // 3: shahcoin.shahswap.v1.QueryPoolResponse
	(*QueryPoolsRequest)(nil),       // 4: shahcoin.shahswap.v1.QueryPoolsRequest
	(*QueryPoolsResponse)(nil),      // 5: shahcoin.shahswap.v1.QueryPoolsResponse
	(*QuerySpotPriceRequest)(nil),   // 6: shahcoin.shahswap.v1.QuerySpotPriceRequest
	(*QuerySpotPriceResponse)(nil),  // 7: shahcoin.shahswap.v1.QuerySpotPriceResponse
	(*QueryLPPositionRequest)(nil),  // 8: shahcoin.shahswap.v1.QueryLPPositionRequest
	(*QueryLPPositionResponse)(nil), // 9: shahcoin.shahswap.v1.QueryLPPositionResponse
	(*Params)(nil),                  // 10: shahcoin.shahswap.v1.Params
	(*Pool)(nil),                    // 11: shahcoin.shahswap.v1.Pool
	(*query.PageRequest)(nil),       // 12: cosmos.base.query.v1beta1.PageRequest
	(*query.PageResponse)(nil),      // 13: cosmos.base.query.v1beta1.PageResponse
	(*LPPosition)(nil),              // 14: shahcoin.shahswap.v1.LPPosition
}
var file_shahcoin_shahswap_v1_query_proto_depIdxs = []int32{
	10, // 0: shahcoin.shahswap.v1.QueryParamsResponse.params:type_name -> shahcoin.shahswap.v1.Params
	11, // 1: shahcoin.shahswap.v1.QueryPoolResponse.pool:type_name -> shahcoin.shahswap.v1.Pool
	12, // 2: shahcoin.shahswap.v1.QueryPoolsRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	11, // 3: shahcoin.shahswap.v1.QueryPoolsResponse.pools:type_name -> shahcoin.shahswap.v1.Pool
	13, // 4: shahcoin.shahswap.v1.QueryPoolsResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	14, // 5: shahcoin.shahswap.v1.QueryLPPositionResponse.position:type_name -> shahcoin.shahswap.v1.LPPosition
	0,  // 6: shahcoin.shahswap.v1.Query.Params:input_type -> shahcoin.shahswap.v1.QueryParamsRequest
	2,  // 7: shahcoin.shahswap.v1.Query.Pool:input_type -> shahcoin.shahswap.v1.QueryPoolRequest
	4,  // 8: shahcoin.shahswap.v1.Query.Pools:input_type -> shahcoin.shahswap.v1.QueryPoolsRequest
	6,  // 9: shahcoin.shahswap.v1.Query.SpotPrice:input_type -> shahcoin.shahswap.v1.QuerySpotPriceRequest
	8,  // 10: shahcoin.shahswap.v1.Query.LPPosition:input_type -> shahcoin.shahswap.v1.QueryLPPositionRequest
	1,  // 11: shahcoin.shahswap.v1.Query.Params:output_type -> shahcoin.shahswap.v1.QueryParamsResponse
	3,  // 12: shahcoin.shahswap.v1.Query.Pool:output_type -> shahcoin.shahswap.v1.QueryPoolResponse
	5,  // 13: shahcoin.shahswap.v1.Query.Pools:output_type -> shahcoin.shahswap.v1.QueryPoolsResponse
	7,  // 14: shahcoin.shahswap.v1.Query.SpotPrice:output_type -> shahcoin.shahswap.v1.QuerySpotPriceResponse
	9,  // 15: shahcoin.shahswap.v1.Query.LPPosition:output_type -> shahcoin.shahswap.v1.QueryLPPositionResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_shahcoin_shahswap_v1_query_proto_init() }
func file_shahcoin_shahswap_v1_query_proto_init() {
	if File_shahcoin_shahswap_v1_query_proto != nil {
		return
	}
	file_shahcoin_shahswap_v1_params_proto_init()
	file_shahcoin_shahswap_v1_pool_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_shahswap_v1_query_proto_rawDesc), len(file_shahcoin_shahswap_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shahcoin_shahswap_v1_query_proto_goTypes,
		DependencyIndexes: file_shahcoin_shahswap_v1_query_proto_depIdxs,
		MessageInfos:      file_shahcoin_shahswap_v1_query_proto_msgTypes,
	}.Build()
	File_shahcoin_shahswap_v1_query_proto = out.File
	file_shahcoin_shahswap_v1_query_proto_goTypes = nil
	file_shahcoin_shahswap_v1_query_proto_depIdxs = nil
}
