// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/monitoring/v1/genesis.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenesisState defines the monitoring module's genesis state.
type GenesisState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// params defines all the parameters of the module.
	Params *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	// metrics holds the current metrics
	Metrics       *Metrics `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_shahcoin_monitoring_v1_genesis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_monitoring_v1_genesis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_shahcoin_monitoring_v1_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *GenesisState) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *GenesisState) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Metrics holds chain metrics
type Metrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalTransactions uint64                 `protobuf:"varint,1,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	ActiveValidators  uint64                 `protobuf:"varint,2,opt,name=active_validators,json=activeValidators,proto3" json:"active_validators,omitempty"`
	TotalSwapVolume   string                 `protobuf:"bytes,3,opt,name=total_swap_volume,json=totalSwapVolume,proto3" json:"total_swap_volume,omitempty"`
	LastBlockTime     int64                  `protobuf:"varint,4,opt,name=last_block_time,json=lastBlockTime,proto3" json:"last_block_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_shahcoin_monitoring_v1_genesis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_monitoring_v1_genesis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_shahcoin_monitoring_v1_genesis_proto_rawDescGZIP(), []int{1}
}

func (x *Metrics) GetTotalTransactions() uint64 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *Metrics) GetActiveValidators() uint64 {
	if x != nil {
		return x.ActiveValidators
	}
	return 0
}

func (x *Metrics) GetTotalSwapVolume() string {
	if x != nil {
		return x.TotalSwapVolume
	}
	return ""
}

func (x *Metrics) GetLastBlockTime() int64 {
	if x != nil {
		return x.LastBlockTime
	}
	return 0
}

var File_shahcoin_monitoring_v1_genesis_proto protoreflect.FileDescriptor

const file_shahcoin_monitoring_v1_genesis_proto_rawDesc = "" +
	"\n" +
	"$shahcoin/monitoring/v1/genesis.proto\x12\x16shahcoin.monitoring.v1\x1a\x14gogoproto/gogo.proto\x1a#shahcoin/monitoring/v1/params.proto\"\x8d\x01\n" +
	"\fGenesisState\x12<\n" +
	"\x06params\x18\x01 \x01(\v2\x1e.shahcoin.monitoring.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\x12?\n" +
	"\ametrics\x18\x02 \x01(\v2\x1f.shahcoin.monitoring.v1.MetricsB\x04\xc8\xde\x1f\x00R\ametrics\"\xd8\x01\n" +
	"\aMetrics\x12-\n" +
	"\x12total_transactions\x18\x01 \x01(\x04R\x11totalTransactions\x12+\n" +
	"\x11active_validators\x18\x02 \x01(\x04R\x10activeValidators\x12I\n" +
	"\x11total_swap_volume\x18\x03 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\x0ftotalSwapVolume\x12&\n" +
	"\x0flast_block_time\x18\x04 \x01(\x03R\rlastBlockTimeB1Z/github.com/shahcoin/shahcoin/x/monitoring/typesb\x06proto3"

var (
	file_shahcoin_monitoring_v1_genesis_proto_rawDescOnce sync.Once
	file_shahcoin_monitoring_v1_genesis_proto_rawDescData []byte
)

func file_shahcoin_monitoring_v1_genesis_proto_rawDescGZIP() []byte {
	file_shahcoin_monitoring_v1_genesis_proto_rawDescOnce.Do(func() {
		file_shahcoin_monitoring_v1_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_monitoring_v1_genesis_proto_rawDesc), len(file_shahcoin_monitoring_v1_genesis_proto_rawDesc)))
	})
	return file_shahcoin_monitoring_v1_genesis_proto_rawDescData
}

var file_shahcoin_monitoring_v1_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shahcoin_monitoring_v1_genesis_proto_goTypes = []any{
	(*GenesisState)(nil), // 0: shahcoin.monitoring.v1.GenesisState
	(*Metrics)(nil),      // 1: shahcoin.monitoring.v1.Metrics
	(*Params)(nil),       // 2: shahcoin.monitoring.v1.Params
}
var file_shahcoin_monitoring_v1_genesis_proto_depIdxs = []int32{
	2, // 0: shahcoin.monitoring.v1.GenesisState.params:type_name -> shahcoin.monitoring.v1.Params
	1, // 1: shahcoin.monitoring.v1.GenesisState.metrics:type_name -> shahcoin.monitoring.v1.Metrics
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shahcoin_monitoring_v1_genesis_proto_init() }
func file_shahcoin_monitoring_v1_genesis_proto_init() {
	if File_shahcoin_monitoring_v1_genesis_proto != nil {
		return
	}
	file_shahcoin_monitoring_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_monitoring_v1_genesis_proto_rawDesc), len(file_shahcoin_monitoring_v1_genesis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shahcoin_monitoring_v1_genesis_proto_goTypes,
		DependencyIndexes: file_shahcoin_monitoring_v1_genesis_proto_depIdxs,
		MessageInfos:      file_shahcoin_monitoring_v1_genesis_proto_msgTypes,
	}.Build()
	File_shahcoin_monitoring_v1_genesis_proto = out.File
	file_shahcoin_monitoring_v1_genesis_proto_goTypes = nil
	file_shahcoin_monitoring_v1_genesis_proto_depIdxs = nil
}
