// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/shahswap/v1/params.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Params defines the parameters for the shahswap module.
type Params struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// trade_fee is the trading fee percentage (e.g., "0.003" for 0.3%)
	TradeFee string `protobuf:"bytes,1,opt,name=trade_fee,json=tradeFee,proto3" json:"trade_fee,omitempty"`
	// protocol_cut is the percentage of fees that go to treasury (e.g., "0.16" for 16%)
	ProtocolCut   string `protobuf:"bytes,2,opt,name=protocol_cut,json=protocolCut,proto3" json:"protocol_cut,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_shahcoin_shahswap_v1_params_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_params_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_params_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetTradeFee() string {
	if x != nil {
		return x.TradeFee
	}
	return ""
}

func (x *Params) GetProtocolCut() string {
	if x != nil {
		return x.ProtocolCut
	}
	return ""
}

var File_shahcoin_shahswap_v1_params_proto protoreflect.FileDescriptor

const file_shahcoin_shahswap_v1_params_proto_rawDesc = "" +
	"\n" +
	"!shahcoin/shahswap/v1/params.proto\x12\x14shahcoin.shahswap.v1\x1a\x14gogoproto/gogo.proto\"\x98\x01\n" +
	"\x06Params\x12@\n" +
	"\ttrade_fee\x18\x01 \x01(\tB#\xc8\xde\x1f\x00\xda\xde\x1f\x1bcosmossdk.io/math.LegacyDecR\btradeFee\x12F\n" +
	"\fprotocol_cut\x18\x02 \x01(\tB#\xc8\xde\x1f\x00\xda\xde\x1f\x1bcosmossdk.io/math.LegacyDecR\vprotocolCut:\x04\x98\xa0\x1f\x00B/Z-github.com/shahcoin/shahcoin/x/shahswap/typesb\x06proto3"

var (
	file_shahcoin_shahswap_v1_params_proto_rawDescOnce sync.Once
	file_shahcoin_shahswap_v1_params_proto_rawDescData []byte
)

func file_shahcoin_shahswap_v1_params_proto_rawDescGZIP() []byte {
	file_shahcoin_shahswap_v1_params_proto_rawDescOnce.Do(func() {
		file_shahcoin_shahswap_v1_params_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_shahswap_v1_params_proto_rawDesc), len(file_shahcoin_shahswap_v1_params_proto_rawDesc)))
	})
	return file_shahcoin_shahswap_v1_params_proto_rawDescData
}

var file_shahcoin_shahswap_v1_params_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shahcoin_shahswap_v1_params_proto_goTypes = []any{
	(*Params)(nil), // 0: shahcoin.shahswap.v1.Params
}
var file_shahcoin_shahswap_v1_params_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shahcoin_shahswap_v1_params_proto_init() }
func file_shahcoin_shahswap_v1_params_proto_init() {
	if File_shahcoin_shahswap_v1_params_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_shahswap_v1_params_proto_rawDesc), len(file_shahcoin_shahswap_v1_params_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shahcoin_shahswap_v1_params_proto_goTypes,
		DependencyIndexes: file_shahcoin_shahswap_v1_params_proto_depIdxs,
		MessageInfos:      file_shahcoin_shahswap_v1_params_proto_msgTypes,
	}.Build()
	File_shahcoin_shahswap_v1_params_proto = out.File
	file_shahcoin_shahswap_v1_params_proto_goTypes = nil
	file_shahcoin_shahswap_v1_params_proto_depIdxs = nil
}
