// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/shahswap/v1/pool.proto

package types

import (
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pool represents a liquidity pool
type Pool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DenomA        string                 `protobuf:"bytes,2,opt,name=denom_a,json=denomA,proto3" json:"denom_a,omitempty"`
	DenomB        string                 `protobuf:"bytes,3,opt,name=denom_b,json=denomB,proto3" json:"denom_b,omitempty"`
	ReserveA      string                 `protobuf:"bytes,4,opt,name=reserve_a,json=reserveA,proto3" json:"reserve_a,omitempty"`
	ReserveB      string                 `protobuf:"bytes,5,opt,name=reserve_b,json=reserveB,proto3" json:"reserve_b,omitempty"`
	TotalLpShares string                 `protobuf:"bytes,6,opt,name=total_lp_shares,json=totalLpShares,proto3" json:"total_lp_shares,omitempty"`
	TotalVolume   string                 `protobuf:"bytes,7,opt,name=total_volume,json=totalVolume,proto3" json:"total_volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pool) Reset() {
	*x = Pool{}
	mi := &file_shahcoin_shahswap_v1_pool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pool) ProtoMessage() {}

func (x *Pool) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_pool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pool.ProtoReflect.Descriptor instead.
func (*Pool) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_pool_proto_rawDescGZIP(), []int{0}
}

func (x *Pool) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pool) GetDenomA() string {
	if x != nil {
		return x.DenomA
	}
	return ""
}

func (x *Pool) GetDenomB() string {
	if x != nil {
		return x.DenomB
	}
	return ""
}

func (x *Pool) GetReserveA() string {
	if x != nil {
		return x.ReserveA
	}
	return ""
}

func (x *Pool) GetReserveB() string {
	if x != nil {
		return x.ReserveB
	}
	return ""
}

func (x *Pool) GetTotalLpShares() string {
	if x != nil {
		return x.TotalLpShares
	}
	return ""
}

func (x *Pool) GetTotalVolume() string {
	if x != nil {
		return x.TotalVolume
	}
	return ""
}

// LPPosition represents a user's liquidity provider position
type LPPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        uint64                 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	LpShares      string                 `protobuf:"bytes,3,opt,name=lp_shares,json=lpShares,proto3" json:"lp_shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LPPosition) Reset() {
	*x = LPPosition{}
	mi := &file_shahcoin_shahswap_v1_pool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LPPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPPosition) ProtoMessage() {}

func (x *LPPosition) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_pool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPPosition.ProtoReflect.Descriptor instead.
func (*LPPosition) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_pool_proto_rawDescGZIP(), []int{1}
}

func (x *LPPosition) GetPoolId() uint64 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *LPPosition) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *LPPosition) GetLpShares() string {
	if x != nil {
		return x.LpShares
	}
	return ""
}

var File_shahcoin_shahswap_v1_pool_proto protoreflect.FileDescriptor

const file_shahcoin_shahswap_v1_pool_proto_rawDesc = "" +
	"\n" +
	"\x1fshahcoin/shahswap/v1/pool.proto\x12\x14shahcoin.shahswap.v1\x1a\x1ecosmos/base/v1beta1/coin.proto\x1a\x14gogoproto/gogo.proto\"\xc9\x02\n" +
	"\x04Pool\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\adenom_a\x18\x02 \x01(\tR\x06denomA\x12\x17\n" +
	"\adenom_b\x18\x03 \x01(\tR\x06denomB\x12:\n" +
	"\treserve_a\x18\x04 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\breserveA\x12:\n" +
	"\treserve_b\x18\x05 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\breserveB\x12E\n" +
	"\x0ftotal_lp_shares\x18\x06 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\rtotalLpShares\x12@\n" +
	"\ftotal_volume\x18\a \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\vtotalVolume\"{\n" +
	"\n" +
	"LPPosition\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\x04R\x06poolId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12:\n" +
	"\tlp_shares\x18\x03 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\blpSharesB/Z-github.com/shahcoin/shahcoin/x/shahswap/typesb\x06proto3"

var (
	file_shahcoin_shahswap_v1_pool_proto_rawDescOnce sync.Once
	file_shahcoin_shahswap_v1_pool_proto_rawDescData []byte
)

func file_shahcoin_shahswap_v1_pool_proto_rawDescGZIP() []byte {
	file_shahcoin_shahswap_v1_pool_proto_rawDescOnce.Do(func() {
		file_shahcoin_shahswap_v1_pool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_shahswap_v1_pool_proto_rawDesc), len(file_shahcoin_shahswap_v1_pool_proto_rawDesc)))
	})
	return file_shahcoin_shahswap_v1_pool_proto_rawDescData
}

var file_shahcoin_shahswap_v1_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shahcoin_shahswap_v1_pool_proto_goTypes = []any{
	(*Pool)(nil),       // 0: shahcoin.shahswap.v1.Pool
	(*LPPosition)(nil), // 1: shahcoin.shahswap.v1.LPPosition
}
var file_shahcoin_shahswap_v1_pool_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shahcoin_shahswap_v1_pool_proto_init() }
func file_shahcoin_shahswap_v1_pool_proto_init() {
	if File_shahcoin_shahswap_v1_pool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_shahswap_v1_pool_proto_rawDesc), len(file_shahcoin_shahswap_v1_pool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shahcoin_shahswap_v1_pool_proto_goTypes,
		DependencyIndexes: file_shahcoin_shahswap_v1_pool_proto_depIdxs,
		MessageInfos:      file_shahcoin_shahswap_v1_pool_proto_msgTypes,
	}.Build()
	File_shahcoin_shahswap_v1_pool_proto = out.File
	file_shahcoin_shahswap_v1_pool_proto_goTypes = nil
	file_shahcoin_shahswap_v1_pool_proto_depIdxs = nil
}
