// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/shahswap/v1/tx.proto

package types

import (
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgCreatePool creates a new liquidity pool
type MsgCreatePool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Creator       string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	CoinA         *types.Coin            `protobuf:"bytes,2,opt,name=coin_a,json=coinA,proto3" json:"coin_a,omitempty"`
	CoinB         *types.Coin            `protobuf:"bytes,3,opt,name=coin_b,json=coinB,proto3" json:"coin_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreatePool) Reset() {
	*x = MsgCreatePool{}
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreatePool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreatePool) ProtoMessage() {}

func (x *MsgCreatePool) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreatePool.ProtoReflect.Descriptor instead.
func (*MsgCreatePool) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgCreatePool) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgCreatePool) GetCoinA() *types.Coin {
	if x != nil {
		return x.CoinA
	}
	return nil
}

func (x *MsgCreatePool) GetCoinB() *types.Coin {
	if x != nil {
		return x.CoinB
	}
	return nil
}

type MsgCreatePoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        uint64                 `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	LpShares      string                 `protobuf:"bytes,2,opt,name=lp_shares,json=lpShares,proto3" json:"lp_shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreatePoolResponse) Reset() {
	*x = MsgCreatePoolResponse{}
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreatePoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreatePoolResponse) ProtoMessage() {}

func (x *MsgCreatePoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreatePoolResponse.ProtoReflect.Descriptor instead.
func (*MsgCreatePoolResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgCreatePoolResponse) GetPoolId() uint64 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *MsgCreatePoolResponse) GetLpShares() string {
	if x != nil {
		return x.LpShares
	}
	return ""
}

// MsgAddLiquidity adds liquidity to a pool
type MsgAddLiquidity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	PoolId        uint64                 `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	CoinA         *types.Coin            `protobuf:"bytes,3,opt,name=coin_a,json=coinA,proto3" json:"coin_a,omitempty"`
	CoinB         *types.Coin            `protobuf:"bytes,4,opt,name=coin_b,json=coinB,proto3" json:"coin_b,omitempty"`
	MinLpShares   string                 `protobuf:"bytes,5,opt,name=min_lp_shares,json=minLpShares,proto3" json:"min_lp_shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAddLiquidity) Reset() {
	*x = MsgAddLiquidity{}
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAddLiquidity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAddLiquidity) ProtoMessage() {}

func (x *MsgAddLiquidity) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAddLiquidity.ProtoReflect.Descriptor instead.
func (*MsgAddLiquidity) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgAddLiquidity) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgAddLiquidity) GetPoolId() uint64 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *MsgAddLiquidity) GetCoinA() *types.Coin {
	if x != nil {
		return x.CoinA
	}
	return nil
}

func (x *MsgAddLiquidity) GetCoinB() *types.Coin {
	if x != nil {
		return x.CoinB
	}
	return nil
}

func (x *MsgAddLiquidity) GetMinLpShares() string {
	if x != nil {
		return x.MinLpShares
	}
	return ""
}

type MsgAddLiquidityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LpShares      string                 `protobuf:"bytes,1,opt,name=lp_shares,json=lpShares,proto3" json:"lp_shares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgAddLiquidityResponse) Reset() {
	*x = MsgAddLiquidityResponse{}
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgAddLiquidityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAddLiquidityResponse) ProtoMessage() {}

func (x *MsgAddLiquidityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAddLiquidityResponse.ProtoReflect.Descriptor instead.
func (*MsgAddLiquidityResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MsgAddLiquidityResponse) GetLpShares() string {
	if x != nil {
		return x.LpShares
	}
	return ""
}

// MsgRemoveLiquidity removes liquidity from a pool
type MsgRemoveLiquidity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	PoolId        uint64                 `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	LpShares      string                 `protobuf:"bytes,3,opt,name=lp_shares,json=lpShares,proto3" json:"lp_shares,omitempty"`
	MinCoinA      string                 `protobuf:"bytes,4,opt,name=min_coin_a,json=minCoinA,proto3" json:"min_coin_a,omitempty"`
	MinCoinB      string                 `protobuf:"bytes,5,opt,name=min_coin_b,json=minCoinB,proto3" json:"min_coin_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRemoveLiquidity) Reset() {
	*x = MsgRemoveLiquidity{}
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRemoveLiquidity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRemoveLiquidity) ProtoMessage() {}

func (x *MsgRemoveLiquidity) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRemoveLiquidity.ProtoReflect.Descriptor instead.
func (*MsgRemoveLiquidity) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgRemoveLiquidity) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgRemoveLiquidity) GetPoolId() uint64 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *MsgRemoveLiquidity) GetLpShares() string {
	if x != nil {
		return x.LpShares
	}
	return ""
}

func (x *MsgRemoveLiquidity) GetMinCoinA() string {
	if x != nil {
		return x.MinCoinA
	}
	return ""
}

func (x *MsgRemoveLiquidity) GetMinCoinB() string {
	if x != nil {
		return x.MinCoinB
	}
	return ""
}

type MsgRemoveLiquidityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoinA         *types.Coin            `protobuf:"bytes,1,opt,name=coin_a,json=coinA,proto3" json:"coin_a,omitempty"`
	CoinB         *types.Coin            `protobuf:"bytes,2,opt,name=coin_b,json=coinB,proto3" json:"coin_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgRemoveLiquidityResponse) Reset() {
	*x = MsgRemoveLiquidityResponse{}
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgRemoveLiquidityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRemoveLiquidityResponse) ProtoMessage() {}

func (x *MsgRemoveLiquidityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRemoveLiquidityResponse.ProtoReflect.Descriptor instead.
func (*MsgRemoveLiquidityResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MsgRemoveLiquidityResponse) GetCoinA() *types.Coin {
	if x != nil {
		return x.CoinA
	}
	return nil
}

func (x *MsgRemoveLiquidityResponse) GetCoinB() *types.Coin {
	if x != nil {
		return x.CoinB
	}
	return nil
}

// MsgSwapExactIn swaps exact amount in
type MsgSwapExactIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	PoolId        uint64                 `protobuf:"varint,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	CoinIn        *types.Coin            `protobuf:"bytes,3,opt,name=coin_in,json=coinIn,proto3" json:"coin_in,omitempty"`
	DenomOut      string                 `protobuf:"bytes,4,opt,name=denom_out,json=denomOut,proto3" json:"denom_out,omitempty"`
	MinAmountOut  string                 `protobuf:"bytes,5,opt,name=min_amount_out,json=minAmountOut,proto3" json:"min_amount_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSwapExactIn) Reset() {
	*x = MsgSwapExactIn{}
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSwapExactIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSwapExactIn) ProtoMessage() {}

func (x *MsgSwapExactIn) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSwapExactIn.ProtoReflect.Descriptor instead.
func (*MsgSwapExactIn) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MsgSwapExactIn) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MsgSwapExactIn) GetPoolId() uint64 {
	if x != nil {
		return x.PoolId
	}
	return 0
}

func (x *MsgSwapExactIn) GetCoinIn() *types.Coin {
	if x != nil {
		return x.CoinIn
	}
	return nil
}

func (x *MsgSwapExactIn) GetDenomOut() string {
	if x != nil {
		return x.DenomOut
	}
	return ""
}

func (x *MsgSwapExactIn) GetMinAmountOut() string {
	if x != nil {
		return x.MinAmountOut
	}
	return ""
}

type MsgSwapExactInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoinOut       *types.Coin            `protobuf:"bytes,1,opt,name=coin_out,json=coinOut,proto3" json:"coin_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSwapExactInResponse) Reset() {
	*x = MsgSwapExactInResponse{}
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSwapExactInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSwapExactInResponse) ProtoMessage() {}

func (x *MsgSwapExactInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSwapExactInResponse.ProtoReflect.Descriptor instead.
func (*MsgSwapExactInResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_tx_proto_rawDescGZIP(), []int{7}
}

func (x *MsgSwapExactInResponse) GetCoinOut() *types.Coin {
	if x != nil {
		return x.CoinOut
	}
	return nil
}

// MsgUpdateParams updates params
type MsgUpdateParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Authority     string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params        *Params                `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParams) Reset() {
	*x = MsgUpdateParams{}
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParams) ProtoMessage() {}

func (x *MsgUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_tx_proto_rawDescGZIP(), []int{8}
}

func (x *MsgUpdateParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateParams) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

type MsgUpdateParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateParamsResponse) Reset() {
	*x = MsgUpdateParamsResponse{}
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateParamsResponse) ProtoMessage() {}

func (x *MsgUpdateParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_shahswap_v1_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_shahswap_v1_tx_proto_rawDescGZIP(), []int{9}
}

var File_shahcoin_shahswap_v1_tx_proto protoreflect.FileDescriptor

const file_shahcoin_shahswap_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x1dshahcoin/shahswap/v1/tx.proto\x12\x14shahcoin.shahswap.v1\x1a\x1ecosmos/base/v1beta1/coin.proto\x1a\x17cosmos/msg/v1/msg.proto\x1a\x14gogoproto/gogo.proto\x1a!shahcoin/shahswap/v1/params.proto\"\xa7\x01\n" +
	"\rMsgCreatePool\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x126\n" +
	"\x06coin_a\x18\x02 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x05coinA\x126\n" +
	"\x06coin_b\x18\x03 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x05coinB:\f\x82\xe7\xb0*\acreator\"l\n" +
	"\x15MsgCreatePoolResponse\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\x04R\x06poolId\x12:\n" +
	"\tlp_shares\x18\x02 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\blpShares\"\x82\x02\n" +
	"\x0fMsgAddLiquidity\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x17\n" +
	"\apool_id\x18\x02 \x01(\x04R\x06poolId\x126\n" +
	"\x06coin_a\x18\x03 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x05coinA\x126\n" +
	"\x06coin_b\x18\x04 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x05coinB\x12A\n" +
	"\rmin_lp_shares\x18\x05 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\vminLpShares:\v\x82\xe7\xb0*\x06sender\"U\n" +
	"\x17MsgAddLiquidityResponse\x12:\n" +
	"\tlp_shares\x18\x01 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\blpShares\"\x88\x02\n" +
	"\x12MsgRemoveLiquidity\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x17\n" +
	"\apool_id\x18\x02 \x01(\x04R\x06poolId\x12:\n" +
	"\tlp_shares\x18\x03 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\blpShares\x12;\n" +
	"\n" +
	"min_coin_a\x18\x04 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\bminCoinA\x12;\n" +
	"\n" +
	"min_coin_b\x18\x05 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\bminCoinB:\v\x82\xe7\xb0*\x06sender\"\x8c\x01\n" +
	"\x1aMsgRemoveLiquidityResponse\x126\n" +
	"\x06coin_a\x18\x01 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x05coinA\x126\n" +
	"\x06coin_b\x18\x02 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x05coinB\"\xea\x01\n" +
	"\x0eMsgSwapExactIn\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x17\n" +
	"\apool_id\x18\x02 \x01(\x04R\x06poolId\x128\n" +
	"\acoin_in\x18\x03 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x06coinIn\x12\x1b\n" +
	"\tdenom_out\x18\x04 \x01(\tR\bdenomOut\x12C\n" +
	"\x0emin_amount_out\x18\x05 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\fminAmountOut:\v\x82\xe7\xb0*\x06sender\"T\n" +
	"\x16MsgSwapExactInResponse\x12:\n" +
	"\bcoin_out\x18\x01 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\acoinOut\"{\n" +
	"\x0fMsgUpdateParams\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12:\n" +
	"\x06params\x18\x02 \x01(\v2\x1c.shahcoin.shahswap.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params:\x0e\x82\xe7\xb0*\tauthority\"\x19\n" +
	"\x17MsgUpdateParamsResponse2\x8a\x04\n" +
	"\x03Msg\x12^\n" +
	"\n" +
	"CreatePool\x12#.shahcoin.shahswap.v1.MsgCreatePool\x1a+.shahcoin.shahswap.v1.MsgCreatePoolResponse\x12d\n" +
	"\fAddLiquidity\x12%.shahcoin.shahswap.v1.MsgAddLiquidity\x1a-.shahcoin.shahswap.v1.MsgAddLiquidityResponse\x12m\n" +
	"\x0fRemoveLiquidity\x12(.shahcoin.shahswap.v1.MsgRemoveLiquidity\x1a0.shahcoin.shahswap.v1.MsgRemoveLiquidityResponse\x12a\n" +
	"\vSwapExactIn\x12$.shahcoin.shahswap.v1.MsgSwapExactIn\x1a,.shahcoin.shahswap.v1.MsgSwapExactInResponse\x12d\n" +
	"\fUpdateParams\x12%.shahcoin.shahswap.v1.MsgUpdateParams\x1a-.shahcoin.shahswap.v1.MsgUpdateParamsResponse\x1a\x05\x80\xe7\xb0*\x01B/Z-github.com/shahcoin/shahcoin/x/shahswap/typesb\x06proto3"

var (
	file_shahcoin_shahswap_v1_tx_proto_rawDescOnce sync.Once
	file_shahcoin_shahswap_v1_tx_proto_rawDescData []byte
)

func file_shahcoin_shahswap_v1_tx_proto_rawDescGZIP() []byte {
	file_shahcoin_shahswap_v1_tx_proto_rawDescOnce.Do(func() {
		file_shahcoin_shahswap_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_shahswap_v1_tx_proto_rawDesc), len(file_shahcoin_shahswap_v1_tx_proto_rawDesc)))
	})
	return file_shahcoin_shahswap_v1_tx_proto_rawDescData
}

var file_shahcoin_shahswap_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_shahcoin_shahswap_v1_tx_proto_goTypes = []any{
	(*MsgCreatePool)(nil),              // 0: shahcoin.shahswap.v1.MsgCreatePool
	(*MsgCreatePoolResponse)(nil),      // 1: shahcoin.shahswap.v1.MsgCreatePoolResponse
	(*MsgAddLiquidity)(nil),            // 2: shahcoin.shahswap.v1.MsgAddLiquidity
	(*MsgAddLiquidityResponse)(nil),    // 3: shahcoin.shahswap.v1.MsgAddLiquidityResponse
	(*MsgRemoveLiquidity)(nil),         // 4: shahcoin.shahswap.v1.MsgRemoveLiquidity
	(*MsgRemoveLiquidityResponse)(nil), // 5: shahcoin.shahswap.v1.MsgRemoveLiquidityResponse
	(*MsgSwapExactIn)(nil),             // 6: shahcoin.shahswap.v1.MsgSwapExactIn
	(*MsgSwapExactInResponse)(nil),     // 7: shahcoin.shahswap.v1.MsgSwapExactInResponse
	(*MsgUpdateParams)(nil),            // 8: shahcoin.shahswap.v1.MsgUpdateParams
	(*MsgUpdateParamsResponse)(nil),    // 9: shahcoin.shahswap.v1.MsgUpdateParamsResponse
	(*types.Coin)(nil),                 // 10: cosmos.base.v1beta1.Coin
	(*Params)(nil),                     // 11: shahcoin.shahswap.v1.Params
}
var file_shahcoin_shahswap_v1_tx_proto_depIdxs = []int32{
	10, // 0: shahcoin.shahswap.v1.MsgCreatePool.coin_a:type_name -> cosmos.base.v1beta1.Coin
	10, // 1: shahcoin.shahswap.v1.MsgCreatePool.coin_b:type_name -> cosmos.base.v1beta1.Coin
	10, // 2: shahcoin.shahswap.v1.MsgAddLiquidity.coin_a:type_name -> cosmos.base.v1beta1.Coin
	10, // 3: shahcoin.shahswap.v1.MsgAddLiquidity.coin_b:type_name -> cosmos.base.v1beta1.Coin
	10, // 4: shahcoin.shahswap.v1.MsgRemoveLiquidityResponse.coin_a:type_name -> cosmos.base.v1beta1.Coin
	10, // 5: shahcoin.shahswap.v1.MsgRemoveLiquidityResponse.coin_b:type_name -> cosmos.base.v1beta1.Coin
	10, // 6: shahcoin.shahswap.v1.MsgSwapExactIn.coin_in:type_name -> cosmos.base.v1beta1.Coin
	10, // 7: shahcoin.shahswap.v1.MsgSwapExactInResponse.coin_out:type_name -> cosmos.base.v1beta1.Coin
	11, // 8: shahcoin.shahswap.v1.MsgUpdateParams.params:type_name -> shahcoin.shahswap.v1.Params
	0,  // 9: shahcoin.shahswap.v1.Msg.CreatePool:input_type -> shahcoin.shahswap.v1.MsgCreatePool
	2,  // 10: shahcoin.shahswap.v1.Msg.AddLiquidity:input_type -> shahcoin.shahswap.v1.MsgAddLiquidity
	4,  // 11: shahcoin.shahswap.v1.Msg.RemoveLiquidity:input_type -> shahcoin.shahswap.v1.MsgRemoveLiquidity
	6,  // 12: shahcoin.shahswap.v1.Msg.SwapExactIn:input_type -> shahcoin.shahswap.v1.MsgSwapExactIn
	8,  // 13: shahcoin.shahswap.v1.Msg.UpdateParams:input_type -> shahcoin.shahswap.v1.MsgUpdateParams
	1,  // 14: shahcoin.shahswap.v1.Msg.CreatePool:output_type -> shahcoin.shahswap.v1.MsgCreatePoolResponse
	3,  // 15: shahcoin.shahswap.v1.Msg.AddLiquidity:output_type -> shahcoin.shahswap.v1.MsgAddLiquidityResponse
	5,  // 16: shahcoin.shahswap.v1.Msg.RemoveLiquidity:output_type -> shahcoin.shahswap.v1.MsgRemoveLiquidityResponse
	7,  // 17: shahcoin.shahswap.v1.Msg.SwapExactIn:output_type -> shahcoin.shahswap.v1.MsgSwapExactInResponse
	9,  // 18: shahcoin.shahswap.v1.Msg.UpdateParams:output_type -> shahcoin.shahswap.v1.MsgUpdateParamsResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_shahcoin_shahswap_v1_tx_proto_init() }
func file_shahcoin_shahswap_v1_tx_proto_init() {
	if File_shahcoin_shahswap_v1_tx_proto != nil {
		return
	}
	file_shahcoin_shahswap_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_shahswap_v1_tx_proto_rawDesc), len(file_shahcoin_shahswap_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shahcoin_shahswap_v1_tx_proto_goTypes,
		DependencyIndexes: file_shahcoin_shahswap_v1_tx_proto_depIdxs,
		MessageInfos:      file_shahcoin_shahswap_v1_tx_proto_msgTypes,
	}.Build()
	File_shahcoin_shahswap_v1_tx_proto = out.File
	file_shahcoin_shahswap_v1_tx_proto_goTypes = nil
	file_shahcoin_shahswap_v1_tx_proto_depIdxs = nil
}
