// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/fees/v1/query.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_shahcoin_fees_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_fees_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_fees_v1_query_proto_rawDescGZIP(), []int{0}
}

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_shahcoin_fees_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_fees_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_fees_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// QueryEstimateTxFeeRequest is the request type for Query/EstimateTxFee
type QueryEstimateTxFeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gas           uint64                 `protobuf:"varint,1,opt,name=gas,proto3" json:"gas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEstimateTxFeeRequest) Reset() {
	*x = QueryEstimateTxFeeRequest{}
	mi := &file_shahcoin_fees_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEstimateTxFeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEstimateTxFeeRequest) ProtoMessage() {}

func (x *QueryEstimateTxFeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_fees_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEstimateTxFeeRequest.ProtoReflect.Descriptor instead.
func (*QueryEstimateTxFeeRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_fees_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryEstimateTxFeeRequest) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

// QueryEstimateTxFeeResponse is the response type for Query/EstimateTxFee
type QueryEstimateTxFeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeeShahi      string                 `protobuf:"bytes,1,opt,name=fee_shahi,json=feeShahi,proto3" json:"fee_shahi,omitempty"`
	FeeUsd        string                 `protobuf:"bytes,2,opt,name=fee_usd,json=feeUsd,proto3" json:"fee_usd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEstimateTxFeeResponse) Reset() {
	*x = QueryEstimateTxFeeResponse{}
	mi := &file_shahcoin_fees_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEstimateTxFeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEstimateTxFeeResponse) ProtoMessage() {}

func (x *QueryEstimateTxFeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_fees_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEstimateTxFeeResponse.ProtoReflect.Descriptor instead.
func (*QueryEstimateTxFeeResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_fees_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryEstimateTxFeeResponse) GetFeeShahi() string {
	if x != nil {
		return x.FeeShahi
	}
	return ""
}

func (x *QueryEstimateTxFeeResponse) GetFeeUsd() string {
	if x != nil {
		return x.FeeUsd
	}
	return ""
}

var File_shahcoin_fees_v1_query_proto protoreflect.FileDescriptor

const file_shahcoin_fees_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1cshahcoin/fees/v1/query.proto\x12\x10shahcoin.fees.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\x1a\x1dshahcoin/fees/v1/params.proto\"\x14\n" +
	"\x12QueryParamsRequest\"M\n" +
	"\x13QueryParamsResponse\x126\n" +
	"\x06params\x18\x01 \x01(\v2\x18.shahcoin.fees.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\"-\n" +
	"\x19QueryEstimateTxFeeRequest\x12\x10\n" +
	"\x03gas\x18\x01 \x01(\x04R\x03gas\"\x96\x01\n" +
	"\x1aQueryEstimateTxFeeResponse\x12:\n" +
	"\tfee_shahi\x18\x01 \x01(\tB\x1d\xc8\xde\x1f\x00\xda\xde\x1f\x15cosmossdk.io/math.IntR\bfeeShahi\x12<\n" +
	"\afee_usd\x18\x02 \x01(\tB#\xc8\xde\x1f\x00\xda\xde\x1f\x1bcosmossdk.io/math.LegacyDecR\x06feeUsd2\x91\x02\n" +
	"\x05Query\x12w\n" +
	"\x06Params\x12$.shahcoin.fees.v1.QueryParamsRequest\x1a%.shahcoin.fees.v1.QueryParamsResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/shahcoin/fees/v1/params\x12\x8e\x01\n" +
	"\rEstimateTxFee\x12+.shahcoin.fees.v1.QueryEstimateTxFeeRequest\x1a,.shahcoin.fees.v1.QueryEstimateTxFeeResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/shahcoin/fees/v1/estimateB+Z)github.com/shahcoin/shahcoin/x/fees/typesb\x06proto3"

var (
	file_shahcoin_fees_v1_query_proto_rawDescOnce sync.Once
	file_shahcoin_fees_v1_query_proto_rawDescData []byte
)

func file_shahcoin_fees_v1_query_proto_rawDescGZIP() []byte {
	file_shahcoin_fees_v1_query_proto_rawDescOnce.Do(func() {
		file_shahcoin_fees_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_fees_v1_query_proto_rawDesc), len(file_shahcoin_fees_v1_query_proto_rawDesc)))
	})
	return file_shahcoin_fees_v1_query_proto_rawDescData
}

var file_shahcoin_fees_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shahcoin_fees_v1_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),         // 0: shahcoin.fees.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),        // 1: shahcoin.fees.v1.QueryParamsResponse
	(*QueryEstimateTxFeeRequest)(nil),  // 2: shahcoin.fees.v1.QueryEstimateTxFeeRequest
	(*QueryEstimateTxFeeResponse)(nil), // 3: shahcoin.fees.v1.QueryEstimateTxFeeResponse
	(*Params)(nil),                     // 4: shahcoin.fees.v1.Params
}
var file_shahcoin_fees_v1_query_proto_depIdxs = []int32{
	4, // 0: shahcoin.fees.v1.QueryParamsResponse.params:type_name -> shahcoin.fees.v1.Params
	0, // 1: shahcoin.fees.v1.Query.Params:input_type -> shahcoin.fees.v1.QueryParamsRequest
	2, // 2: shahcoin.fees.v1.Query.EstimateTxFee:input_type -> shahcoin.fees.v1.QueryEstimateTxFeeRequest
	1, // 3: shahcoin.fees.v1.Query.Params:output_type -> shahcoin.fees.v1.QueryParamsResponse
	3, // 4: shahcoin.fees.v1.Query.EstimateTxFee:output_type -> shahcoin.fees.v1.QueryEstimateTxFeeResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shahcoin_fees_v1_query_proto_init() }
func file_shahcoin_fees_v1_query_proto_init() {
	if File_shahcoin_fees_v1_query_proto != nil {
		return
	}
	file_shahcoin_fees_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_fees_v1_query_proto_rawDesc), len(file_shahcoin_fees_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shahcoin_fees_v1_query_proto_goTypes,
		DependencyIndexes: file_shahcoin_fees_v1_query_proto_depIdxs,
		MessageInfos:      file_shahcoin_fees_v1_query_proto_msgTypes,
	}.Build()
	File_shahcoin_fees_v1_query_proto = out.File
	file_shahcoin_fees_v1_query_proto_goTypes = nil
	file_shahcoin_fees_v1_query_proto_depIdxs = nil
}
