// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shahcoin/monitoring/v1/query.proto

package types

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_shahcoin_monitoring_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_monitoring_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_monitoring_v1_query_proto_rawDescGZIP(), []int{0}
}

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        *Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_shahcoin_monitoring_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_monitoring_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_monitoring_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// QueryMetricsRequest is the request type for Query/Metrics
type QueryMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetricsRequest) Reset() {
	*x = QueryMetricsRequest{}
	mi := &file_shahcoin_monitoring_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetricsRequest) ProtoMessage() {}

func (x *QueryMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_monitoring_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetricsRequest.ProtoReflect.Descriptor instead.
func (*QueryMetricsRequest) Descriptor() ([]byte, []int) {
	return file_shahcoin_monitoring_v1_query_proto_rawDescGZIP(), []int{2}
}

// QueryMetricsResponse is the response type for Query/Metrics
type QueryMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *Metrics               `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetricsResponse) Reset() {
	*x = QueryMetricsResponse{}
	mi := &file_shahcoin_monitoring_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetricsResponse) ProtoMessage() {}

func (x *QueryMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shahcoin_monitoring_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetricsResponse.ProtoReflect.Descriptor instead.
func (*QueryMetricsResponse) Descriptor() ([]byte, []int) {
	return file_shahcoin_monitoring_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryMetricsResponse) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_shahcoin_monitoring_v1_query_proto protoreflect.FileDescriptor

const file_shahcoin_monitoring_v1_query_proto_rawDesc = "" +
	"\n" +
	"\"shahcoin/monitoring/v1/query.proto\x12\x16shahcoin.monitoring.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\x1a#shahcoin/monitoring/v1/params.proto\x1a$shahcoin/monitoring/v1/genesis.proto\"\x14\n" +
	"\x12QueryParamsRequest\"S\n" +
	"\x13QueryParamsResponse\x12<\n" +
	"\x06params\x18\x01 \x01(\v2\x1e.shahcoin.monitoring.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\"\x15\n" +
	"\x13QueryMetricsRequest\"W\n" +
	"\x14QueryMetricsResponse\x12?\n" +
	"\ametrics\x18\x01 \x01(\v2\x1f.shahcoin.monitoring.v1.MetricsB\x04\xc8\xde\x1f\x00R\ametrics2\xa3\x02\n" +
	"\x05Query\x12\x89\x01\n" +
	"\x06Params\x12*.shahcoin.monitoring.v1.QueryParamsRequest\x1a+.shahcoin.monitoring.v1.QueryParamsResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/shahcoin/monitoring/v1/params\x12\x8d\x01\n" +
	"\aMetrics\x12+.shahcoin.monitoring.v1.QueryMetricsRequest\x1a,.shahcoin.monitoring.v1.QueryMetricsResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/shahcoin/monitoring/v1/metricsB1Z/github.com/shahcoin/shahcoin/x/monitoring/typesb\x06proto3"

var (
	file_shahcoin_monitoring_v1_query_proto_rawDescOnce sync.Once
	file_shahcoin_monitoring_v1_query_proto_rawDescData []byte
)

func file_shahcoin_monitoring_v1_query_proto_rawDescGZIP() []byte {
	file_shahcoin_monitoring_v1_query_proto_rawDescOnce.Do(func() {
		file_shahcoin_monitoring_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shahcoin_monitoring_v1_query_proto_rawDesc), len(file_shahcoin_monitoring_v1_query_proto_rawDesc)))
	})
	return file_shahcoin_monitoring_v1_query_proto_rawDescData
}

var file_shahcoin_monitoring_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shahcoin_monitoring_v1_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),   // 0: shahcoin.monitoring.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),  // 1: shahcoin.monitoring.v1.QueryParamsResponse
	(*QueryMetricsRequest)(nil),  // 2: shahcoin.monitoring.v1.QueryMetricsRequest
	(*QueryMetricsResponse)(nil), // 3: shahcoin.monitoring.v1.QueryMetricsResponse
	(*Params)(nil),               // 4: shahcoin.monitoring.v1.Params
	(*Metrics)(nil),              // 5: shahcoin.monitoring.v1.Metrics
}
var file_shahcoin_monitoring_v1_query_proto_depIdxs = []int32{
	4, // 0: shahcoin.monitoring.v1.QueryParamsResponse.params:type_name -> shahcoin.monitoring.v1.Params
	5, // 1: shahcoin.monitoring.v1.QueryMetricsResponse.metrics:type_name -> shahcoin.monitoring.v1.Metrics
	0, // 2: shahcoin.monitoring.v1.Query.Params:input_type -> shahcoin.monitoring.v1.QueryParamsRequest
	2, // 3: shahcoin.monitoring.v1.Query.Metrics:input_type -> shahcoin.monitoring.v1.QueryMetricsRequest
	1, // 4: shahcoin.monitoring.v1.Query.Params:output_type -> shahcoin.monitoring.v1.QueryParamsResponse
	3, // 5: shahcoin.monitoring.v1.Query.Metrics:output_type -> shahcoin.monitoring.v1.QueryMetricsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shahcoin_monitoring_v1_query_proto_init() }
func file_shahcoin_monitoring_v1_query_proto_init() {
	if File_shahcoin_monitoring_v1_query_proto != nil {
		return
	}
	file_shahcoin_monitoring_v1_params_proto_init()
	file_shahcoin_monitoring_v1_genesis_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shahcoin_monitoring_v1_query_proto_rawDesc), len(file_shahcoin_monitoring_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shahcoin_monitoring_v1_query_proto_goTypes,
		DependencyIndexes: file_shahcoin_monitoring_v1_query_proto_depIdxs,
		MessageInfos:      file_shahcoin_monitoring_v1_query_proto_msgTypes,
	}.Build()
	File_shahcoin_monitoring_v1_query_proto = out.File
	file_shahcoin_monitoring_v1_query_proto_goTypes = nil
	file_shahcoin_monitoring_v1_query_proto_depIdxs = nil
}
